Add redirect for /sign-in on www
supabase/supabase pull request #10509
Opened 2022-11-24 09:52 UTC by joshenlim

2022-11-24 09:53 UTC, alaister approved these changes

2022-11-24 09:56 UTC, MildTomato requested changes

2022-11-24 09:56 UTC, MildTomato commented on apps/www/lib/redirects.js
> +  },
missing 'sign-up' redirect

2022-11-24 09:58 UTC, joshenlim commented on apps/www/lib/redirects.js
> +  },
gotcha, added

2022-11-24 09:59 UTC, alaister commented on apps/www/lib/redirects.js
> +  },
Worth adding forgot password, too, then?

2022-11-24 15:56 UTC, joshenlim commented on apps/www/lib/redirects.js
> +  },
yup! added

2022-11-25 02:42 UTC, MildTomato approved these changes

2022-11-25 02:42 UTC, merged