Add Picket Auth Integration Guide
supabase/supabase pull request #10618
Opened 2022-11-29 18:48 UTC by devstein

Hi 👋 

## What kind of change does this PR introduce?

Documentation on how to integrate [Picket](https://picketapi.com/) with Supabase to enable wallet login for users that want to build hybrid web 2/3 apps. The new docs are an adaptation of the existing [Picket + Supabase docs](https://docs.picketapi.com/picket-docs/reference/integrations/supabase) in the [Picket documentation](https://docs.picketapi.com/).

#### Common Use-Case for Picket + Supabase
-   Account linking. Allow users to associate their wallet address(es) with their existing web2 account in your app
-   Leverage Supabase's awesome libraries and ecosystem while still enabling wallet login
-   Store app-specific data, like user preferences, about your user's wallet adress off-chain
-   Cache on-chain data to improve your DApp's performance

## What is the current behavior?

N/A

## What is the new behavior?

N/A

## Additional context

I've been emailing @thorwebdev

2022-12-05 05:06 UTC, thorwebdev commented
@devstein thanks so much for this. Quick heads up that we're sprinting towards [Launch Week](https://supabase.com/launch-week) right now and might be a bit delayed in reviewing this, sorry!

2023-01-09 08:05 UTC, thorwebdev requested changes
Some changes needed to apply the page styling correctly.

2023-01-09 21:59 UTC, devstein commented on apps/docs/components/Navigation/Navigation.constants.ts
> +            { name: 'Picket', url: '/guides/integrations/picket', items: [] },
done

2023-01-10 03:55 UTC, thorwebdev approved these changes
LGTM, thanks.

2023-01-10 03:56 UTC, thorwebdev commented
@devstein sorry, the prettier check is failing. Can you either run prettier or allow me to push to your repo?

2023-01-10 15:43 UTC, devstein commented
Hi @thorwebdev I ran prettier on `picket.mdx`, but if I run the repo-level `npm run format` the diff is quite large. Regardless, gave you write access to the repo. 

I also noticed that the `package.json` command doesn't include `.mdx` files but the CI check appears to

```json
    "format": "prettier --write \"apps/**/*.{js,jsx,ts,tsx,css,md,json}\"",
```

Thanks!

2023-01-11 03:02 UTC, merged