fix: add mfa reference docs
supabase/supabase pull request #10838
Opened 2022-12-10 20:04 UTC by kangmingtay

## What kind of change does this PR introduce?
* Add MFA methods to reference docs

2022-12-11 03:54 UTC, dannykng commented on spec/common-client-libs-sections.json
> +        "title": "Verify a challenge",
Should this be:
```suggestion
        "title": "Create and verify a challenge",
```

2022-12-11 03:54 UTC, dannykng commented on spec/supabase_js_v2_temp_new_shape.yml
> +      - To generate a QR code containing the `totp` secret,
Incomplete sentence?

2022-12-11 03:54 UTC, dannykng commented on spec/supabase_js_v2_temp_new_shape.yml
> +        name: Enroll a Time-based One time password (TOTP) factor
```suggestion
        name: Enroll a time-based, one-time password (TOTP) factor
```

2022-12-11 03:54 UTC, dannykng commented on spec/supabase_js_v2_temp_new_shape.yml
> +        name: Creates a challenge for a factor
```suggestion
        name: Create a challenge for a factor
```

2022-12-11 03:54 UTC, dannykng commented on spec/supabase_js_v2_temp_new_shape.yml
> +        name: Verifies a challenge for a factor
```suggestion
        name: Verify a challenge for a factor
```

2022-12-11 03:54 UTC, dannykng commented on spec/supabase_js_v2_temp_new_shape.yml
> +        name: Creates and verifies a challenge for a factor
```suggestion
        name: Create and verify a challenge for a factor
```

2022-12-11 03:54 UTC, dannykng commented on spec/supabase_js_v2_temp_new_shape.yml
> +      - In Supabase, having an AAL of `aal1` typically refers to having the 1st factor of authentication such as an email and password or oauth sign-in while `aal2` refers to the 2nd factor of authen
```suggestion
      - In Supabase, having an AAL of `aal1` refers to having the 1st factor of authentication such as an email and password or OAuth sign-in while `aal2` refers to the 2nd factor of authentication such as a time-based, one-time-password (TOTP).
```

2022-12-11 03:54 UTC, dannykng commented on spec/supabase_js_v2_temp_new_shape.yml
> +        name: List all factors associated to a user
For consistency:
```suggestion
        name: List all factors for a user
```

2022-12-11 03:54 UTC, dannykng commented on spec/supabase_js_v2_temp_new_shape.yml
> +        name: Deletes a factor associated to a user
```suggestion
        name: Delete a factor for a user
```

2022-12-13 00:11 UTC, dannykng approved these changes

2022-12-13 04:32 UTC, MildTomato commented
<img width="825" alt="Screenshot 2022-12-13 at 12 31 50 PM" src="https://user-images.githubusercontent.com/8291514/207227152-6e4de936-ac5c-4cdd-8720-8891f0d4f9ea.png">

make sure Docs has built preview before merging

2022-12-13 04:47 UTC, MildTomato commented
<img width="380" alt="Screenshot 2022-12-13 at 12 46 56 PM" src="https://user-images.githubusercontent.com/8291514/207229045-e35054bc-7d22-40f1-ad97-9ef8110a188d.png">

we also need to be vigilent about these enrichment changes.
make sure they are actually new updated ones when they change

2022-12-13 04:59 UTC, MildTomato approved these changes

2022-12-13 08:14 UTC, MildTomato commented
Whats going on with these enrichments? 
@kangmingtay are you running `make` in the `/spec` directory ? or copying things over manually ?

2022-12-13 08:15 UTC, MildTomato requested changes
blocked merging while clarifying enrichment issue

2022-12-13 08:30 UTC, MildTomato approved these changes

2022-12-13 08:31 UTC, MildTomato commented
snuck missing env vars for ticket site in

2022-12-13 09:04 UTC, merged