feat: introduce team plan to dashboard
supabase/supabase pull request #11341
Opened 2022-12-29 13:25 UTC by kevcodez

Introduces the self-serve up/downgrade for the Team tier

2022-12-30 17:32 UTC, alaister requested changes
This looks great! I tried it out, and it all seems to be working 🎉

There's one change to do with Tailwind that I've detailed below. I'd also like @joshenlim to take a look at this when he gets back, as he knows the most about the billing section of the dashboard.

2022-12-31 12:31 UTC, kevcodez commented on studio/components/interfaces/Billing/PlanSelection/PlanSelection.tsx
> +        <div className={`grid lg:grid-cols-${tiers.length} gap-8 py-8`}>
Adjusted

2022-12-31 12:31 UTC, kevcodez commented on studio/components/interfaces/Billing/PlanSelection/PlanSelection.utils.ts
> +    .filter((it) => it)
Adjusted

2023-01-03 07:57 UTC, joshenlim commented
just going through this now - UI needs to change slightly on the /settings/billing/update page - with 4 cards its looking a little squeezy now, will make the changes

2023-01-04 04:44 UTC, joshenlim commented
Decided that we'll get this through to staging first and improve the UI in subsequent PRs since this is behind a flag either way - @alaister could you help +1 this PR?

2023-01-04 16:34 UTC, alaister approved these changes
LGTM!

2023-01-05 15:41 UTC, merged