First pass at reducing number of radix colours
supabase/supabase pull request #11602
Opened 2023-01-12 03:15 UTC by saltcod

— excludes Radix colours we import to just the ones we need
— cleans up ui package to use the common tailwind config
— removes some config duplication

2023-02-16 17:57 UTC, Ziinc approved these changes
👍 LGTM

2023-04-18 03:40 UTC, MildTomato commented on packages/config/ui.config.js
> +  'bronze',
we use bronze

2023-04-18 03:42 UTC, MildTomato commented on packages/config/ui.config.js
> +  'crimson',
we use crimson in auth ui example

2023-04-18 03:42 UTC, MildTomato commented on packages/config/ui.config.js
> +  'gold',
we use gold in some LW stuff

2023-04-18 03:43 UTC, MildTomato commented on packages/config/ui.config.js
> +  'indigo',
we use indigo on realtime marketing page

2023-04-18 03:44 UTC, MildTomato commented on packages/config/ui.config.js
> +  'pink',
used in LW page

2023-04-18 03:45 UTC, MildTomato commented on packages/config/ui.config.js
> +  'purple',
we use purple in LW

2023-04-18 03:46 UTC, MildTomato commented on packages/config/ui.config.js
> +  'sand',
sand used once here
https://github.com/supabase/supabase/blob/master/studio/pages/join/index.tsx/#L183-L186

2023-04-18 03:47 UTC, MildTomato commented on packages/config/ui.config.js
> +  'tomato',
tomato used in realtime marketing page

2023-04-18 03:47 UTC, MildTomato commented on packages/config/ui.config.js
> +  'violet',
violet used once here
https://github.com/supabase/supabase/blob/master/apps/www/pages/beta.tsx/#L56

2023-04-18 03:49 UTC, MildTomato commented on packages/ui/package.json
> +    "config": "*",
huh?

2023-04-18 03:49 UTC, MildTomato commented on packages/ui/src/lib/theme/defaultTheme.ts
>        yellow: `bg-yellow-200 text-yellow-1100 border border-yellow-700`,
can remove any color on here in the excluded list above

2023-04-18 03:50 UTC, MildTomato requested changes

2023-04-18 03:50 UTC, MildTomato commented on packages/config/ui.config.js
> +  'crimson',
leaving a review comment to ask for changes. see comments above.

2023-04-18 12:38 UTC, MildTomato approved these changes

2023-04-18 13:49 UTC, merged