Add blog post for type constraints (domains)
supabase/supabase pull request #11916
Opened 2023-01-25 14:32 UTC by olirice

## What kind of change does this PR introduce?
Adds a blog post for domain types in Postgres

2023-01-25 14:34 UTC, olirice commented on apps/www/_blog/2023-01-25-type-constraints-in-50-lines-of-sql.mdx
> +thumb:
TODO: image here

2023-01-25 14:34 UTC, olirice commented on apps/www/_blog/2023-01-25-type-constraints-in-50-lines-of-sql.mdx
> +<IMAGE HERE>
TODO: image here that is comparable to
<img width="386" alt="Screenshot 2023-01-25 at 8 34 35 AM" src="https://user-images.githubusercontent.com/12958657/214591070-de67c30a-d224-47fa-ae26-6c7bf1a33c07.png">

2023-02-16 20:50 UTC, w3b6x9 approved these changes

2023-02-16 21:52 UTC, alaister requested changes

2023-02-16 21:52 UTC, alaister commented on apps/www/_blog/2023-01-25-type-constraints-in-65-lines-of-sql.mdx
> +![image](/images/blog/2023-jan/semver-spec.png)
I think this is a `.jpg`, not a `.png`

2023-02-16 22:01 UTC, alaister requested changes, later dismissed

2023-02-16 22:01 UTC, alaister commented on apps/www/_blog/2023-01-25-type-constraints-in-65-lines-of-sql.mdx
> + 1 | supabase-js, | (2,0,0,"{rc,1}",)
Is the `,` wanted in `supabase-js,`?

2023-02-16 22:01 UTC, alaister commented on apps/www/_blog/2023-01-25-type-constraints-in-65-lines-of-sql.mdx
> + 1 | supabase-js, | 2.0.0-rc.1
More `,`

2023-02-17 14:25 UTC, merged