Feat/ssl enforcement
supabase/supabase pull request #12250
Opened 2023-02-08 09:29 UTC by joshenlim

Normal state:
![Screenshot 2023-02-08 at 5 22 54 PM](https://user-images.githubusercontent.com/19742402/217489142-88d76e2e-96a4-4d83-a3cc-f9b0e81f2f85.png)

Error state:
![Screenshot 2023-02-08 at 5 28 45 PM](https://user-images.githubusercontent.com/19742402/217489876-6f61bab2-485b-4ea3-aeed-2fef505c5b67.png)

2023-02-08 09:36 UTC, darora commented on studio/components/interfaces/Settings/Database/SSLConfiguration.tsx
> +                    Reject connections made to your database without a valid certificate
`without a valid certificate` makes it sound like we're enforcing client cert auth, which we're not. Would suggest "Rejects non-SSL connections to your database" or "Rejects unsecure connections to your database" to keep it simple.

2023-02-09 04:25 UTC, alaister requested changes
Looking good! Appreciate the cleanup too. Just one tiny thing:

2023-02-09 04:25 UTC, alaister commented on studio/data/ssl-enforcement/ssl-enforcement-update-mutation.ts
> +        await queryClient.invalidateQueries(sslEnforcementKeys.list(projectRef)),
Cheeky trailing comma here

2023-02-09 06:19 UTC, alaister approved these changes
LGTM!

2023-02-09 06:19 UTC, merged