Use live and open-api proxy
supabase/supabase pull request #12696
Opened 2023-02-27 03:51 UTC by joshenlim

2023-02-27 10:26 UTC, alaister requested changes
Working great!
If you could make the graphiql change, that would be great. As for the react-query one, it's more my wishful thinking – so I will approve without it if you want to get this in :)

2023-02-27 10:26 UTC, alaister commented on studio/components/interfaces/GraphQL/GraphiQL.tsx
> +      defaultHeaders={JSON.stringify({ Authorization: `Bearer ${accessToken}` })}
We'll only want to show the headers if an access token exists to edit. Something like `defaultHeaders={accessToken ? JSON.stringify({ Authorization: `Bearer ${accessToken}` }) : undefined}`

2023-02-28 07:48 UTC, joshenlim commented on studio/pages/project/[ref]/api/graphiql.tsx
> +    fetchAccessToken()
donee!

2023-02-28 07:52 UTC, alaister approved these changes

2023-02-28 08:05 UTC, merged