[Docs] Spend cap guide
supabase/supabase pull request #12878
Opened 2023-03-08 04:10 UTC by MildTomato

## What kind of change does this PR introduce?

New guide for spend cap

2023-03-08 06:44 UTC, kiwicopple commented on apps/docs/pages/guides/platform/spend-cap.mdx
> +For managing cost control for each project, there is a Spend Cap to manage your usage and costs.
```suggestion
Supabase offers a "Spend Cap" on each project to manage your usage and costs.
```

2023-03-08 06:45 UTC, kiwicopple commented on apps/docs/pages/guides/platform/spend-cap.mdx
> +Each project's Spend Cap determines wether your project can exceed the free quota allowance of any paid [line item](#what-can-i-be-charged-for) in a given billing cycle.
```suggestion
This Spend Cap determines whether your project can exceed the free quota allowance of any [line item](#what-can-i-be-charged-for) in a given billing cycle.
```

2023-03-08 06:46 UTC, kiwicopple commented on apps/docs/pages/guides/platform/spend-cap.mdx
> +## What happens when the Spend Cap is on
```suggestion
## What happens when the Spend Cap is on?
```

2023-03-08 06:48 UTC, kiwicopple commented on apps/docs/pages/guides/platform/spend-cap.mdx
> +Once you use all the free quota allowance for a [line item](#what-can-i-be-charged-for), your project will continually be able to make further usage.
```suggestion
Your project will continue to operate after using all the free quota allowance for each [line item](#what-can-i-be-charged-for).
```

2023-03-08 06:49 UTC, kiwicopple commented on apps/docs/pages/guides/platform/spend-cap.mdx
> +  It is advised, when your Spend Cap is **off**, to monitor your usage and costs using the [Usage
```suggestion
  When your Spend Cap is **off**, we recommend monitoring your consumption and costs using the [Usage
```

2023-03-09 00:59 UTC, kevcodez requested changes
Just one small change and a nit - great to get some docs for billing 👏

2023-03-09 00:59 UTC, kevcodez commented on apps/docs/pages/guides/platform/spend-cap.mdx
> +- Realtime connections
```suggestion
```

We only have the peak connections as a line item, not the connections itself

2023-03-09 00:59 UTC, kevcodez commented on apps/docs/components/Navigation/NavigationMenu/NavigationMenu.constants.ts
> +      name: 'Billing Management',
```suggestion
      name: 'Billing',
```

Up to you though, I'd prefer the short version

2023-03-09 04:53 UTC, kevcodez approved these changes

2023-03-10 08:28 UTC, merged