docs(guides/database/full-text-search) update searching multiple columns
supabase/supabase pull request #13110
Opened 2023-03-20 15:25 UTC by khairulhaaziq

## What kind of change does this PR introduce?

Update searching multiple columns guide (js and dart) with a workaround involving computed virtual columns

Solution by @steve-chahez from this https://github.com/supabase/postgrest-js/issues/289

Bug fix, feature, docs update, ...

## What is the current behavior?

Please link any relevant issues here.

https://github.com/supabase/supabase/pull/12508
https://github.com/supabase/postgrest-js/issues/289

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2023-03-20 23:06 UTC, gregnr requested changes
@khairulhaaziq This is great, thanks for the PR! Just a couple format consistency changes and we'll be good to merge.

2023-03-20 23:06 UTC, gregnr commented on apps/docs/pages/guides/database/full-text-search.mdx
> +Right now there is no direct way to use Javascript or Dart to search through multiple columns. A workaround exist where using SQL is required.
```suggestion
Right now there is no direct way to use JavaScript or Dart to search through multiple columns. A workaround exist where using SQL is required.
```

2023-03-20 23:06 UTC, gregnr commented on apps/docs/pages/guides/database/full-text-search.mdx
> +$$ LANGUAGE SQL;
```suggestion
create function title_description(books) returns text as $$
  select $1.title || ' ' || $1.description;
$$ language sql;
```

2023-03-20 23:06 UTC, gregnr commented on apps/docs/pages/guides/database/full-text-search.mdx
> +$$ LANGUAGE SQL;
```suggestion
create function title_description(books) returns text as $$
  select $1.title || ' ' || $1.description;
$$ language sql;
```

2023-03-21 07:08 UTC, alaister reviewed
@khairulhaaziq, Thanks for this PR!

@steve-chavez, should these functions for the computed columns be marked as `immutable`? Or will it not make a difference in this context?

2023-03-21 07:08 UTC, alaister commented on apps/docs/pages/guides/database/full-text-search.mdx
> +$$ language sql;
```suggestion
$$ language sql immutable;
```

2023-03-21 07:08 UTC, alaister commented on apps/docs/pages/guides/database/full-text-search.mdx
> +$$ language sql;
```suggestion
$$ language sql immutable;
```

2023-03-21 14:22 UTC, khairulhaaziq commented
@steve-chavez @gregnr @alaister I applied all the suggestions. Please let me know if there are things to be adjusted/fixed!

2023-03-21 15:51 UTC, steve-chavez approved these changes
LGTM. Thanks!

2023-03-21 15:59 UTC, gregnr approved these changes

2023-03-21 16:08 UTC, merged