delete default button
supabase/supabase pull request #13306
Opened 2023-03-30 01:04 UTC by Isaiah-Hamilton

## What kind of change does this PR introduce?

Delete default button in the common folder for turborepo.

2023-03-30 03:51 UTC, alaister requested changes
Thanks, Isaiah,
Could you also go through the code and ensure there aren't any references to this button component? I found one in `apps/temp-community-forum/src/pages/index.tsx` for example (it's unused, but still means the build would fail in future)

2023-03-31 12:12 UTC, kiwicopple approved these changes

2023-03-31 12:12 UTC, kiwicopple commented
we can probably delete `temp-community-forum` and `temp-community-tutorials` too. Seems like they aren't getting used

2023-03-31 19:53 UTC, MildTomato commented
@alaister those sites no longer exist ;)

2023-04-03 03:41 UTC, alaister approved these changes

2023-04-03 04:21 UTC, merged