docs: Updated RedwoodJS Quick Start with Prisma
supabase/supabase pull request #13454
Opened 2023-04-05 11:40 UTC by dthyresson

## What kind of change does this PR introduce?

This PR follows the basic outline of the other framework QuickStarts to create and populate and list a handful of Countries:

* Adds a RedwoodJS Framework Quick Start that showcases how to use RedwoodJS with Prisma and Supabase as its Postgres database. It describes how to create a project, configure Redwood and Prisma, use Prisma migrations and seeds to creamer and populate the schema and then build a CRUD UI scaffold to manage Countries.

* Syncs up the menu of QuickStarts with the content cards. Some items were missing.

## What is the current behavior?

Currently, there is no RedwoodJS framework quickstart, only the previous Guide aka Web Tutorial (which will also be updated).

## What is the new behavior?

### All Quickstarts listed

![Screenshot 2023-04-05 at 7 39 17 AM](https://user-images.githubusercontent.com/1051633/230069767-dd5de668-31f3-4f6d-a3d6-7054d963b9dd.png)

## RedwoodJS Quickstart

![Screenshot 2023-04-05 at 7 37 13 AM](https://user-images.githubusercontent.com/1051633/230069400-0971b61b-0b76-477e-9def-db03ebb6ec27.png)
![Screenshot 2023-04-05 at 7 37 21 AM](https://user-images.githubusercontent.com/1051633/230069397-bc788227-6773-4606-b42a-3df482f7f9ce.png)
![Screenshot 2023-04-05 at 7 37 29 AM](https://user-images.githubusercontent.com/1051633/230069394-1f67bff0-695d-4d49-9d8e-e79a2e192aea.png)
![Screenshot 2023-04-05 at 7 37 36 AM](https://user-images.githubusercontent.com/1051633/230069391-af81a25d-1a75-44b0-bff1-5ae86b8c5497.png)
![Screenshot 2023-04-05 at 7 37 44 AM](https://user-images.githubusercontent.com/1051633/230069386-fc303105-50c0-42a8-80f0-b256cdf6d5fa.png)

## Additional context

This PR is for Supabase Launch Week 7.

Note: the Web Tutorial is next to be updated and will have more advanced setup, such as how to use RLS with Prisma.

2023-04-05 11:43 UTC, dthyresson commented
I just noticed "Start the App" was duplicated in the heading. Fixing.

2023-04-05 19:12 UTC, gregnr requested changes, later dismissed
Great, thanks for putting this together @dthyresson! 😃 Just a minor fix and we can merge this.

2023-04-05 19:12 UTC, gregnr commented on apps/docs/pages/guides/getting-started/quickstarts/redwoodjs.mdx
> +  <StepHikeCompact.Step step={5}>
Looks like we got two step 5's here 👀

2023-04-06 13:41 UTC, dthyresson commented
> Great, thanks for putting this together @dthyresson! 😃 Just a minor fix and we can merge this.

Thanks! I renumbered the steps and also cleaned up the whitespace and formatting (am used to having prettier setup and only now realized my indentation was off everywhere).

I still would like the redwoodJS team to review, but I think it's good to merge and we can always update and improve.

2023-04-07 10:55 UTC, kiwicopple approved these changes

2023-04-07 10:56 UTC, merged