Add README file for Indonesian
supabase/supabase pull request #1374
Opened 2021-05-02 13:05 UTC by Anjianto

## What kind of change does this PR introduce?

Add README file for Indonesian

## What is the current behavior?

- 

## What is the new behavior?

- ![Screenshot from 2021-05-02 20-04-22](https://user-images.githubusercontent.com/61521141/116814172-a908f700-ab81-11eb-87ff-d2a21c5f8e2b.png)

## Additional context

-

2021-05-02 13:26 UTC, GetItBac92 requested changes
Who approved these changes

2021-05-03 00:55 UTC, AngSanley commented
I think the first sentence "Supabase adalah sumber terbuka alternatif Firebase" is a bit wrong. It sounded like a computer-translated sentence. 

It should be "Supabase adalah alternatif sumber terbuka dari Firebase"

Also, "kita" (reader included) in the second sentence should be "kami" (reader excluded).

2021-05-04 01:12 UTC, Anjianto commented
> I think the first sentence "Supabase adalah sumber terbuka alternatif Firebase" is a bit wrong. It sounded like a computer-translated sentence.
> 
> It should be "Supabase adalah alternatif sumber terbuka dari Firebase"
> 
> Also, "kita" (reader included) in the second sentence should be "kami" (reader excluded).

"Supabase adalah sumber terbuka alternatif Firebase" this is purely from me, not from computer-translated.

'Also, "kita" (reader included) in the second sentence should be "kami" (reader excluded).' Oh yeah, sorry i'm forgot about it.

2021-05-04 01:19 UTC, kiwicopple commented
Thanks everyone - also note that we split the "Languages" section out to a separate file: 
https://github.com/supabase/supabase/blob/master/i18n/languages.md

2021-05-17 06:40 UTC, dnswd requested changes
This is a fairly nice translation, but I agree with @AngSanley. There are lots of lines that can be improved.

2021-05-17 06:40 UTC, dnswd commented on i18n/README.id.md
> +- [Email Support](https://supabase.io/docs/support#business-support). Terbaik untuk: masalah - masalah dengan database atau infrastrukturkamu
There should be a space between `infrastruktur` and `kamu`.

2021-05-17 06:40 UTC, dnswd commented on i18n/README.id.md
> +- [x] Dashboard
You can use `Dasbor` to replace `Dashboard`. But you can leave it as is, it's fine already.

2021-05-17 06:40 UTC, dnswd commented on i18n/README.id.md
> +- [x] Alpha: Kita test Supabase dengan sejumlah pelanggan tertutup.
This sounds too stiff, you can improve it by replacing `test` with `menguji`. Also I think it's better to add `secara` between `pelanggan` and `tertutup`.

`Kami menguji Supabase dengan sejumlah pelanggan secara tertutup` sounds a bit better.

2021-05-17 06:40 UTC, dnswd commented on i18n/README.id.md
> +Supabase adalah kombinasi dari alat - alat sumber terbuka. Kita mengembangkan fitur Firebase menggunakan produk sumber terbuka kelas perusahaan. Jika alat - alat dan komunias - komunitas ada, dengan
- Delete spaces between hypen:
  - `alat - alat` to `alat-alat`
  - `komunitas - komunitas` to `komunitas-komunitas`


- > Supabase tidak 1 untuk 1 pemetaan Firebase.  Tujuan kami adalah untuk memberi pengembang sebuah pengalaman seperti Firebase pengembang menggunakan alat -alat sumber terbuka.

  This sounded like a computer-translated sentence. You can rephrase this.

- Several typos.

2021-05-17 06:40 UTC, dnswd commented on i18n/README.id.md
> +Supabase adalah sebuah [platform yang dihosting](https://app.supabase.io). Kamu bisa daftar dan mulai menggunakan Supabase tanpa menginstall apapun. Kita tetap membuat pengalaman mengembakan di lokal
- The standard translation for `install` is `pasang`. So you can replace `menginstall` with `memasang`.

- > selama dengan platform yang stabil.

  I don't think this is the correct translation.

2021-05-17 06:40 UTC, dnswd commented on i18n/README.id.md
> +- [PostgreSQL](https://www.postgresql.org/) adalah obejct relational database sistem dengan pengembangan aktif lebih dari 30 tahun yang membuatnya memiliki reputasi yang kuat untuk keandalan, fitur k
This translation is also sounds off.

2021-05-17 07:10 UTC, Nisaju approved these changes

2021-05-17 07:14 UTC, closed without merging