feat: tell users which email supabase support will respond to
supabase/supabase pull request #14103
Opened 2023-05-03 10:55 UTC by loong

## What is the current behavior?

Currently, it's not visible where users will receive responses from support. It can cause some confusion, especially for those who login with github and not using their github email anymore.

## What is the new behavior?

Showing a short notice that we will email them. Also lets user know to which email we will send responses to.

<img width="689" alt="Screenshot 2023-05-03 at 6 52 31 PM" src="https://user-images.githubusercontent.com/1732217/235896849-d937e168-5045-4869-8f8d-71fe45033802.png">

2023-05-03 11:16 UTC, joshenlim commented on studio/components/interfaces/Support/SupportForm.tsx
> +    get(`${API_URL}/profile`).then((data) => {
update to use the `useProfileQuery`, which will remove the need for a state + useEffect

2023-05-03 11:17 UTC, joshenlim requested changes
just a small change 🙏

2023-05-04 00:44 UTC, loong commented
@joshenlim made the change. please check, not sure if using onSuccess() is how it is suppose to be used!

2023-05-04 00:47 UTC, alaister commented
@loong you can remove the `respondToEmail` state entry and do something like:
```tsx
const { data: profile } = useProfileQuery()
const respondToEmail = profile?. primary_email ?? ''
```

2023-05-04 00:56 UTC, loong commented
@alaister thanks! updated it. small change so hope we can deploy soon!

2023-05-04 05:50 UTC, joshenlim approved these changes

2023-05-04 06:25 UTC, merged