Make navbar sticky and FlyOut menu full width
supabase/supabase pull request #1519
Opened 2021-05-10 19:36 UTC by florian-lefebvre

## What kind of change does this PR introduce?

Improvement

## What is the current behavior?

The navbar is not sticky, so the user has to scroll to the top to access the links. Also, the FlyOut component is weird because he is not full width.

## What is the new behavior?

The navbar is now sticky and the FlyOut component is now full width.

## Additional context

I have modified the Nav and the beta page to move the FlyOut menu to the right location, according to the new implementation.
Also, I put a `Fragment` in the Nav to prepare my next PR.

2021-05-11 02:42 UTC, MildTomato requested changes
hey @florian-lefebvre - nice work! just a broken logo needs fixing I think

2021-05-11 06:00 UTC, florian-lefebvre commented on www/components/Nav/index.tsx
> +    <Fragment>
Oh cool! I come from Vue some I learn React while doing thoses PRs 😄

2021-05-16 08:16 UTC, florian-lefebvre commented on www/components/Nav/index.tsx
> +      {/* Announcement Nav */}
@MildTomato I just deleted it

2021-05-17 05:06 UTC, MildTomato commented
sorry for delay, i'll take a look

2021-05-17 05:09 UTC, MildTomato approved these changes
lgtm 😄  thanks @florian-lefebvre !

2021-05-17 05:09 UTC, merged