Passing JWT_SECRET and JWT_EXPIRY to postgrest APP_SETTINGS
supabase/supabase pull request #16681
Opened 2023-08-22 00:23 UTC by Lan-Hekary

## What kind of change does this PR introduce?

This PR allow the user to get the JWT Secret and expiry inside postgres using `current_setting('app.settings.jwt_secret')` and `current_setting('app.settings.jwt_expiry')`

## What is the current behavior?

Supabase managed instances can get the JWT_SECRET through executing the query `current_setting('app.settings.jwt_secret')` , But Self-hosted instances can't do that because the these values are not passed in the application setting for postgrest.

## What is the new behavior?

Passing the Values as environment variables to postgrest services as mentioned [here](https://postgrest.org/en/stable/references/configuration.html#app-settings) align the behavior of self-hosted services with supabase managed instances.

2023-08-22 10:00 UTC, soedirgo approved these changes

2023-08-28 16:49 UTC, sweatybridge requested changes
Could you confirm these env vars are working as expected for you? I'm still getting an error from my local self-hosted setup.

```bash
$ psql -h localhost -U postgres -p 5432
Password for user postgres:
psql (15.3, server 15.1 (Ubuntu 15.1-1.pgdg20.04+1))
Type "help" for help.

postgres=> select current_setting('app.settings.jwt_secret');
ERROR:  unrecognized configuration parameter "app.settings.jwt_secret"
```

2023-08-28 17:39 UTC, steve-chavez commented
> postgres=> select current_setting('app.settings.jwt_secret');
ERROR:  unrecognized configuration parameter "app.settings.jwt_secret"

@sweatybridge The above would only work if you're inside a [PostgREST transaction](https://postgrest.org/en/stable/references/transactions.html). Like when executing a function/RPC.

2023-08-28 17:57 UTC, Lan-Hekary commented
Hello @sweatybridge,
as @steve-chavez  said, its working only inside a PostggREST Transaction. 
meaning that it works only if called from the REST Endpoint.

2023-08-29 02:15 UTC, sweatybridge approved these changes

2023-08-29 11:09 UTC, Lan-Hekary commented
It satisfies my use case for a degree, but I am thinking that it's better to be exposed through out the DB like with the Supabase hosted version.

So, Should we add an initialisation script to the DB instead ?
I see you already did that in the CLI, if it's okay let me know And I will work on it, or if you prefer to do it its okay as well.

2023-08-30 00:46 UTC, soedirgo commented
I'll merge this for now, but feel free to add a db init script in another PR if you need to 👍

2023-08-30 00:46 UTC, merged