Fix: Twitter logo in TweetCard component
supabase/supabase pull request #16794
Opened 2023-08-24 20:53 UTC by monicakh

## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Twitter logo needs to be fixed as it was showing only a black icon:
![image](https://github.com/supabase/supabase/assets/99693443/37e5a04d-8ee2-4a95-bae1-2623cc10e596)

## What is the new behavior?

![image](https://github.com/supabase/supabase/assets/99693443/0519dcd9-9b9a-4ba5-84fb-2f7bc61eba4e)

2023-08-25 07:34 UTC, fsansalvadore submitted a review, later dismissed

2023-08-25 07:38 UTC, fsansalvadore commented
@monicakh Are you still not seeing a white X?

I noticed the X on your version now renders a bit off. I think it's the svg viewport.

2023-08-25 07:40 UTC, fsansalvadore requested changes
This should keep it the correct size

2023-08-25 07:40 UTC, fsansalvadore commented on apps/www/components/TweetCard.tsx
> +              viewBox="0 0 32 32"
```suggestion
              viewBox="0 0 24 24"
```

2023-08-26 10:29 UTC, monicakh commented
@fsansalvadore Yeah it's still not rendering on my end but it's only happening on Chrome.

2023-09-13 00:43 UTC, Isaiah-Hamilton commented
This issue seems to be working fine in production. Is this issue only happening on your computer, local dev or browser?

2023-11-17 10:44 UTC, closed without merging