Fix duplicate key
supabase/supabase pull request #16820
Opened 2023-08-25 15:53 UTC by saltcod

"Issues with Apis" and "Abuse report" have the same value:  "Problem" 
So both get selected when one of them is selected.  

![CleanShot 2023-08-25 at 13 22 08@2x](https://github.com/supabase/supabase/assets/105593/b001233f-e512-445f-ac01-7fd180067814)

2023-08-26 09:09 UTC, joshenlim commented on studio/components/interfaces/Support/Support.constants.ts
> +    value: 'Abuse',
before we get this in, just need to double check on API's end whether this is a valid category

2023-08-26 09:10 UTC, joshenlim commented on studio/components/interfaces/Support/Support.constants.ts
> +    value: 'Abuse',
yeah these are the available support categories so this change will send the support ticket to feedback instead

![image](https://github.com/supabase/supabase/assets/19742402/9bf78181-782b-4405-8278-4eaa4db1774d)

2023-08-26 09:11 UTC, joshenlim commented on studio/components/interfaces/Support/Support.constants.ts
> +    value: 'Abuse',
while you're on this PR @saltcod would you mind just changing the values to using `SupportCategories` from shared-types? will help us prevent any sort of deviance between FE and API

but yeah these comments are separate to the issue that you're fixing in this PR, may need a different solution

2023-08-26 09:12 UTC, joshenlim requested changes
Left some comments but TLDR, 'Abuse' as a category is not supported and will not be funnelled into the support flow

2023-08-30 17:37 UTC, saltcod commented on studio/components/interfaces/Support/SupportForm.tsx
> +              severity: initialValues.severity,
Issue: 
https://supabase.slack.com/archives/C0161K73J1J/p1693412541497319?thread_ts=1693404721.979579&cid=C0161K73J1J

2023-08-30 19:16 UTC, saltcod commented
Depends on
https://github.com/supabase/shared-types/pull/46

2023-09-05 05:43 UTC, joshenlim commented
lgtm! tested every category on the preview - works :)

2023-09-05 05:46 UTC, joshenlim approved these changes

2023-09-05 05:58 UTC, merged