docs: update around email template
supabase/supabase pull request #16970
Opened 2023-08-29 15:01 UTC by J0

## What kind of change does this PR introduce?

introduces the `sendingTo` field for email change flows which would allow devs to customize between the two emails that are sent out: the email to the current email and the email to the proposed new email.

2023-08-29 22:00 UTC, kangmingtay requested changes

2023-08-29 22:00 UTC, kangmingtay commented on studio/stores/authConfig/schema/AuthProviders/AuthTemplatesValidation.tsx
> +- \`{{ .SendingTo }}\: The recipient of the email. Relevant for Secure Email Change.`
maybe a link to the docs explaining why it's relevant when the "Secure Email Change" setting is enabled would be more useful here

2023-08-29 22:00 UTC, kangmingtay commented on apps/docs/pages/guides/auth/auth-email-templates.mdx
> +```
can we give an example of why this is useful (i.e. for the token hash validation)?

2024-01-24 06:36 UTC, J0 commented on apps/docs/pages/guides/auth/auth-email-templates.mdx
> +Let's demonstrate some ways of using the templating system below:
```suggestion
```

2024-01-24 06:58 UTC, kangmingtay approved these changes

2024-01-24 06:58 UTC, J0 commented on apps/docs/pages/guides/auth/auth-email-templates.mdx
> +{{end }}
```suggestion
{{ end }}
```

2024-01-24 07:18 UTC, merged