fix: $ in front of column name causes issue with definition tab
supabase/supabase pull request #17087
Opened 2023-08-31 21:57 UTC by Bhavyawahie

## What kind of change does this PR introduce?

Fixes [#17013](https://github.com/supabase/supabase/issues/17013). The given PR brings about **client-side validation** on column's `name` field for a given table's definition made using the `Table Editor.`  

## What is the current behavior?

The current behavior allows for naming columns of a given table without any validation for special characters `(case in point being column names beginning with'$')` which cause a syntax error with the supabase-meta container running the postgres-meta service.

> <img src="https://github.com/supabase/supabase/assets/34278282/bc3dbbcb-4608-4aef-8c57-57e7d7cc2cef" width="500" height="320"/>

###  **Replicating the error**

> ![ezgif com-video-to-gif (11)](https://github.com/supabase/supabase/assets/34278282/bb7faa3f-0daa-427c-aaad-ef798037c756)

###  **Error from Postgres-meta container's logs**

> ```shell
> "request":{"method":"POST","url":"/query","pg":"db","opt":""}}
> {"level":"error","time":"2023-08-31T11:31:36.849Z","pid":19,"hostname":"a26f486d93cb","reqId":"req-2st","error":{"message":"syntax error at or near \"$\""}," \"$\""}
> ``` 

## What is the new behavior?

The changes in validation allow for users to not create a table until the said column name within that table do not begin with a '$'. Additionally, any previously created column names are also validated on any subsequent updation to them.

### **Table Creation**

> ![ezgif com-video-to-gif (13)](https://github.com/supabase/supabase/assets/34278282/f316b3ef-8377-4ec7-bd2c-62ebe91bf572)

### **Table Updation**

> ![ezgif com-video-to-gif (12)](https://github.com/supabase/supabase/assets/34278282/40f5d456-5515-4b82-9110-b9432f2b4536)

### **Accessing Table Definition**

> ![ezgif com-video-to-gif (14)](https://github.com/supabase/supabase/assets/34278282/fd2401e1-691f-42da-8746-cbfc2c80bd26)

This also solves the problem of `Application error` that was earlier caused by column names beginning with '$' on accessing the Table Definition tab inside the Table Editor.

2023-08-31 21:57 UTC, Bhavyawahie commented
@alaister have a look!

2023-09-01 06:45 UTC, kiwicopple commented on studio/components/interfaces/TableGridEditor/SidePanelEditor/TableEditor/ColumnManagement.tsx
> +                        Recommended to use lowercase (must not begin with $)  and use an underscore to separate words e.g.
```suggestion
                        Recommended to use only lowercase letters, with an underscore to separate words e.g.
```

2023-09-01 08:09 UTC, alaister requested changes
Hey @Bhavyawahie,

Thanks for the PR!

While not recommended, it is supported in postgres to name columns beginning with `$`. For example, we also allow columns with spaces in the name. Additionally, this doesn't seem to fix the definitions tab error for people who already have columns named with `$`.

With this in mind, could you remove this new validation and fix the bug in the definitions tab? I'm happy to help out with some pointers if it isn't clear where the error might be (I have a feeling it might be in our SQL formatted library 😕)

Thanks!

2023-09-01 09:34 UTC, Bhavyawahie commented
Thanks for the feedback @alaister. Happy to work as instructed although I feel this validation check is also necessary at this point until the said changes in the definitions tab are proposed/made. 

The SQL editor also disallows to name/rename column names with `column_name` beginning with $ sign or any special character for that matter `(/^[a-zA-Z_][a-zA-Z0-9_]*$/)` thus may cause irregularities in the UI as far as SQL column nomenclature rules across the platform is concerned.
 
> 
![image](https://github.com/supabase/supabase/assets/34278282/5d4eaef6-ff2d-4fb8-9e32-ce4b4e9af120)

2023-09-04 05:57 UTC, alaister commented
Postgres (SQL) is doing the validation, which is causing that error to happen in the SQL editor. If you wrap the column name containing the `$` or spaces with double quotes (`"`) it will work. So do you think you can make the changes to the definitions tab here in this PR? 🙏🏻

2023-09-04 07:33 UTC, Bhavyawahie commented
Sure, given if you could point me to where the error might be 😅🙏

2023-09-20 14:32 UTC, rmrt1n commented
This is `sql-formatter`'s parsing error caused by `pg_get_tabledef` returning unquoted `$column_name`. Updating `pg_get_tabledef` to quote column/table names starting with `$` should fix the issue (like below):
![image](https://github.com/supabase/supabase/assets/51780559/b897f21f-d225-4a3d-95fc-ea1c26d1223f)

However, column names with spaces in them, as shown above, are still broken. Handling quoted identifiers is tricky. Currently, `pg_get_tabledef` quotes columns that are: 1. contains a capital letter, and 2. is a reserved keyword. A quick workaround is to quote every column in the table.

A better(?) approach might look like this:
1. quote reserved keywords
2. quote all columns that doesn't follow postgres's valid identifer syntax: `/^[a-z_][a-zA-Z0-9_$]$/`. This should include columns that are camelCase, $dollar_sign, and "contains spaces".

This should probably fix most parse issues related to table/column names. Unfortunately this doesn't take into account identifiers that contain non-latin characters. Any thoughts @alaister ?

2024-09-19 06:15 UTC, alaister commented
Hi,

Unfortunately, this has got a little stale, so I'm going to go ahead and close it.

I think this issue should be solved on the https://github.com/MichaelDBA/pg_get_tabledef side, so maybe you can consider opening up an issue there? Thanks 🙏🏻

2024-09-19 06:15 UTC, closed without merging