Feat/secrets management edge functions
supabase/supabase pull request #17518
Opened 2023-09-18 10:00 UTC by joshenlim

2023-09-18 10:26 UTC, inian commented
We shouldn't show the delete button for [reserved secrets](https://github.com/supabase/infrastructure/blob/cc4375015c91d14ee263c0447957c173e2d1d7e0/api/src/routes/v1/projects/ref/secrets/secrets.controller.ts#L126)

2023-09-18 15:07 UTC, alaister requested changes
Looking great! Found a couple small things:

2023-09-19 05:06 UTC, joshenlim commented on studio/components/interfaces/Functions/EdgeFunctionSecrets/EdgeFunctionSecret.tsx
> +            <Input copy value={secret.value} size="small" className="font-mono w-full" />
ahh yes - inian left a comment on this too that this is the "digest" i'll need to rename the headers and won't need to hide the values
behaviour should match CLI

2023-09-19 05:07 UTC, joshenlim commented on studio/components/interfaces/Functions/EdgeFunctionSecrets/EdgeFunctionSecrets.tsx
> +    projectRef: projectRef ?? '',
ahh yeah this shouldn't be on local/self-hosted

2023-09-19 07:34 UTC, alaister approved these changes
LGTM!

2023-09-19 09:14 UTC, merged