feat: add editing support for `citext` data type in table editor
supabase/supabase pull request #17666
Opened 2023-09-23 07:29 UTC by kishanhitk

## What kind of change does this PR introduce?

feature

## What is the current behavior?
Columns of `citext` are not editable, as the current logic assumes it to be an enum.

![image](https://github.com/supabase/supabase/assets/41117038/ec42a453-6989-49db-b1e8-06d5d33e103a)

Fixes: #17451
## What is the new behavior?
Columns of `citext` are treated as text columns, and are editable as text.

![image](https://github.com/supabase/supabase/assets/41117038/76a59bc2-6b8f-4cc9-bb55-9a51111d2303)

## Additional context

2023-09-25 11:47 UTC, ivasilov requested changes
hey @kishanhitk, instead of expanding `isTextColumn`, can you define a new function `isCiTextColumn` and add in the `if-else` chain beneath `isTextColumn`? I think that approach is clearer.

2023-09-25 13:08 UTC, kishanhitk commented
Thanks @ivasilov,
I have made the suggested change, and also added `citext` as one of the possible types in `ColumnType`.
Does it look good now?

2023-09-29 10:42 UTC, ivasilov approved these changes

2023-09-29 10:43 UTC, ivasilov commented
@kishanhitk Thank you for your contribution. Merging.

2023-09-29 10:47 UTC, merged