Chore/nudge project cards
supabase/supabase pull request #17857
Opened 2023-10-02 19:40 UTC by saltcod

Reduce visual weight of status badges on project cards 

<img width="791" alt="screenshot-2023-10-02-at-17 10 03" src="https://github.com/supabase/supabase/assets/105593/02474b8e-bc1a-4625-9f0f-7e084396f5ad">

2023-10-03 15:32 UTC, MildTomato requested changes

2023-10-03 15:32 UTC, MildTomato commented on studio/components/interfaces/Home/ProjectList/ProjectCardStatus.tsx
> +        <div className="flex justify-between items-center w-full pr-0.5">
do we need the extra `<div>` ?

2023-10-03 15:40 UTC, MildTomato approved these changes

2023-10-04 05:36 UTC, joshenlim approved these changes

2023-10-04 05:36 UTC, merged