Update example card
supabase/supabase pull request #17945
Opened 2023-10-05 02:07 UTC by Isaiah-Hamilton

## What kind of change does this PR introduce?

Update example card to match current UI.

## What is the current behavior?

![CleanShot 2023-10-04 at 22 05 29@2x](https://github.com/supabase/supabase/assets/70828596/ed240bc7-fe67-47f5-96d1-81bd24d43a79)

## What is the new behavior?

![CleanShot 2023-10-04 at 22 05 33@2x](https://github.com/supabase/supabase/assets/70828596/dac2a1f0-69af-4269-aa1d-eb89a7658aa2)

## Additional context

Didn't know if I should keep or get rid of the color separation or the creator image/name.

2023-12-04 09:47 UTC, fsansalvadore requested changes

2023-12-04 09:47 UTC, fsansalvadore commented on apps/www/components/ExampleCard.tsx
> +            </a>
With next13 now next/link `<Link>` component is self contained, you don't need the inner `<a>` tag.
So you can remove the <a> tag. Also, the <Button> component should be outside using `asChild` prop.

Like this:
```tsx
<Button size="tiny" type="default" iconRight={<IconArrowUpRight />} asChild>
  <Link href={props.repo_url} target="_blank">
    View Code
  </Link>
</Button>
```

2023-12-04 09:47 UTC, fsansalvadore commented on apps/www/components/ExampleCard.tsx
> +            </Link>
Same as above

2023-12-04 09:47 UTC, fsansalvadore commented on apps/www/components/ExampleCard.tsx
> +              <a target="_blank">
Same here, you can remove the <a> tag and move `target` to the Link tag.

2023-12-04 09:47 UTC, fsansalvadore commented on apps/www/components/ExampleCard.tsx
> +            <p className="text-light">{props.description}</p>
```suggestion
            <p className="text-sm">{props.description}</p>
```

2023-12-04 09:47 UTC, fsansalvadore commented on apps/www/components/ExampleCard.tsx
> +          <h2 className="text text-lg font-medium">{props.title}</h2>
```suggestion
          <h2 className="text text-sm font-medium">{props.title}</h2>
```

2024-01-28 19:08 UTC, Isaiah-Hamilton commented
Closing because the component is no longer being used.

2024-01-28 19:08 UTC, closed without merging