Update functions.mdx
supabase/supabase pull request #18332
Opened 2023-10-19 11:40 UTC by mansueli

## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2023-10-19 11:43 UTC, kevcodez approved these changes

2023-10-19 11:46 UTC, kevcodez requested changes

2023-10-19 11:46 UTC, kevcodez commented on apps/docs/pages/guides/functions.mdx
> +    href: '/guides/functions/examples/slack-bot-mention',
Leads to 404

2023-10-19 11:59 UTC, mansueli commented on apps/docs/pages/guides/functions.mdx
> +    href: '/guides/functions/examples/slack-bot-mention',
Fixed now

2023-10-20 12:06 UTC, kevcodez approved these changes

2023-10-20 12:56 UTC, merged