docs: update with-ionic-angular.mdx
supabase/supabase pull request #18613
Opened 2023-10-31 11:17 UTC by bobbyg603

## What kind of change does this PR introduce?

Docs update

## What is the current behavior?

The samples from the ionic docs are outdated and don't compile in the latest versions of ionic/Angular.

## What is the new behavior?

The samples compile and runs. Additionally, the email input on the account page was blanks so I fixed that as well.

## Additional context

* Fix compile errors
* Update syntax to match @supabase/supabase-js v2
* Correct spelling/grammar mistakes found by Grammarly

I waffled a bit on what to do about the untyped errors. I opted for any because the point of this tutorial is a minimal demonstration of supabase that's approachable to a beginner/intermediate level developer. With that in mind, it felt more important to keep the code concise instead of type-checking errors in every catch block.  I'm open to feedback here.

Additionally, I was indecisive about handling the API change regarding returning errors instead of throwing them. I opted to throw the error immediately if one was returned because that was the only way I could guarantee that the sample snippets worked the same as before this update without doing a deep dive. I'm open to feedback here as well.

2023-10-31 11:18 UTC, bobbyg603 commented on apps/docs/pages/guides/getting-started/tutorials/with-ionic-angular.mdx
> +      .then(({ data}) => data?.session)
```suggestion
      .then(({ data }) => data?.session)
```

2023-12-14 16:08 UTC, burggraf requested changes, later dismissed
One quick change you should make:
change:
`ts environment.ts` to `src/environments/environment.ts`

2023-12-14 16:08 UTC, burggraf commented on apps/docs/pages/guides/getting-started/tutorials/with-ionic-angular.mdx
One quick change you should make:
change:
`ts environment.ts` to `src/environments/environment.ts`

2023-12-14 21:26 UTC, bobbyg603 commented on apps/docs/pages/guides/getting-started/tutorials/with-ionic-angular.mdx
> +And finally, we want to save the environment variables in the `environment.ts` file.
```suggestion
And finally, we want to save the environment variables in the `src/environments/environment.ts` file.
```

2023-12-14 21:27 UTC, bobbyg603 commented on apps/docs/pages/guides/getting-started/tutorials/with-ionic-angular.mdx
thanks for the review, addressed this in 🙂 [3799e67](https://github.com/supabase/supabase/pull/18613/commits/3799e678dc4e02ac0f74de7f70555a1bfc1c3bb7)

2023-12-20 14:20 UTC, bobbyg603 commented
hi @burggraf, can you please approve/merge? thank you!

2023-12-20 17:35 UTC, charislam approved these changes

2023-12-20 17:35 UTC, charislam commented on apps/docs/pages/guides/getting-started/tutorials/with-ionic-angular.mdx
> +Let's set up a route to manage logins and sign-ups. We'll use Magic Links so users can sign in with their email without using passwords.
```suggestion
Let's set up a route to manage logins and signups. We'll use Magic Links so users can sign in with their email without using passwords.
```

2023-12-20 17:35 UTC, charislam commented on apps/docs/pages/guides/getting-started/tutorials/with-ionic-angular.mdx
> +Create a **LoginPage** with `ionic g page login` Ionic CLI command.
```suggestion
Create a **LoginPage** with the `ionic g page login` Ionic CLI command.
```

2023-12-20 17:35 UTC, charislam commented on apps/docs/pages/guides/getting-started/tutorials/with-ionic-angular.mdx
> +Now that we have all the components in place let's update **AppComponent**:
```suggestion
Now that we have all the components in place, let's update **AppComponent**:
```

2023-12-20 17:37 UTC, charislam commented
LGTM, thanks for this one!

2023-12-20 22:15 UTC, bobbyg603 commented
> LGTM, thanks for this one!

Thanks for the review @charislam! I noticed the merge was blocked by the prettier build rule. I ran prettier and pushed a commit. Can you please re-enable auto-merge? Thank you!

2023-12-21 19:50 UTC, merged

2023-12-21 20:58 UTC, bobbyg603 commented
Thanks for merging this @charislam 🎉!