Improved the auth/callback doc to solve the url bug
supabase/supabase pull request #18734
Opened 2023-11-05 14:44 UTC by vinayakhegde1

## What kind of change does this PR introduce?

This PR improves the doc to fix auth/callback url error #18730

## What is the current behavior?

 Issue #18730

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context
Updated the code as per the given improvement in #18730

2023-11-05 17:07 UTC, Crayon-ShinChan requested changes

2023-11-05 17:07 UTC, Crayon-ShinChan commented on apps/docs/pages/guides/auth/server-side/oauth-with-pkce-flow-for-ssr.mdx
>  import { createServerClient, type CookieOptions } from '@supabase/ssr'
the import is duplicated

2023-11-05 17:55 UTC, vinayakhegde1 commented on apps/docs/pages/guides/auth/server-side/oauth-with-pkce-flow-for-ssr.mdx
>  import { createServerClient, type CookieOptions } from '@supabase/ssr'
@Crayon-ShinChan removed the line

2023-11-05 23:30 UTC, Crayon-ShinChan approved these changes

2023-11-07 17:43 UTC, charislam approved these changes

2023-11-07 17:45 UTC, charislam commented
Thanks @vinayakhegde1! Much appreciated.

Looks good, but it seems like your formatter might be different from our formatter as the Prettier check is failing. Do you mind reformatting this so we can merge?

2023-11-10 13:32 UTC, vinayakhegde1 commented
@charislam sure but if you can help me exactly how can I  achieve that

2023-11-13 17:04 UTC, charislam commented
The check that is failing is this: `npx prettier -c '{apps,studio}/**/*.{js,jsx,ts,tsx,css,md,mdx,json}'`

If you run `npx prettier '{apps,studio}/**/*.{js,jsx,ts,tsx,css,md,mdx,json}'`, it should reformat the code to match our style guide. If that breaks things, you can also [prettier-ignore](https://prettier.io/docs/en/ignore.html) this section

2023-11-13 18:00 UTC, Oms-343 commented
hello @charislam  ,   @Crayon-ShinChan  I  have created the pull request for the same and added @vinayakhegde1 as a co-author here #18923 .

2023-11-14 17:50 UTC, silentworks approved these changes

2023-11-14 18:24 UTC, merged

2023-11-21 01:12 UTC, Crayon-ShinChan commented
Actually doc here also need to be improved with the same problem https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr