Migrate Lottie animation
supabase/supabase pull request #19922
Opened 2023-12-20 19:06 UTC by fsansalvadore

## What kind of change does this PR introduce?

- Migrate Loader animation from Lottie to plain css
- remove lottie-light-react package 

https://github.com/supabase/supabase/assets/25671831/9973c4e4-e7f4-40ff-a680-2dd0afc9401a

2023-12-20 21:06 UTC, kevcodez requested changes
Ts check failing too, can't wait to merge, awesome work

2023-12-20 21:06 UTC, kevcodez commented on apps/studio/components/layouts/ProjectLayout/ProjectLayout.tsx
> +  if (true) {
Needs to be reverted here

2023-12-21 00:27 UTC, kevcodez approved these changes

2023-12-21 00:27 UTC, kevcodez commented on apps/studio/components/ui/Loading/Loading.tsx
> +export default Loading
Should we get rid of this component, considering it does nothing but re-export LogoLoader?

2023-12-21 07:39 UTC, alaister approved these changes

2023-12-21 07:45 UTC, merged