chore: update themes and add dark-new theme set
supabase/supabase pull request #20865
Opened 2024-01-30 11:15 UTC by MildTomato

## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2024-02-12 08:23 UTC, MildTomato commented
- [ ] There is an issue with active states on icon side bar

2024-02-12 08:30 UTC, ivasilov approved these changes

2024-02-12 08:33 UTC, ivasilov commented
The SQL editor looks broken. The RLS editor looks like it's using the old dark.
![Screenshot 2024-02-12 at 09 31 26](https://github.com/supabase/supabase/assets/568291/6cc84f30-8297-4174-bc58-412c50dfbc3a)
![Screenshot 2024-02-12 at 09 32 18](https://github.com/supabase/supabase/assets/568291/64dfcf53-11c0-4991-acb1-8994d56e831f)

2024-02-12 09:09 UTC, MildTomato commented
@ivasilov 

> The SQL editor looks broken.

This seems like the current behavior. It flashes white before setting the dark mode.

2024-02-14 15:37 UTC, fsansalvadore commented on apps/www/styles/index.css
> +  @apply bg-background text-foreground;
@MildTomato I just added this `text-foreground` to the body selector to fix some inheritance styling issues.

<img width="1493" alt="Screenshot 2024-02-14 at 16 35 05" src="https://github.com/supabase/supabase/assets/25671831/935ed1d7-223c-4807-8382-167e55be10c3">

2024-02-14 16:23 UTC, fsansalvadore commented
@MildTomato fyi you can still pick the `deep-dark` theme via the command menu.

2024-02-14 16:58 UTC, fsansalvadore requested changes
@MildTomato you can still pick the deep-dark theme via the command menu.
Prob need to filter the incoming themes how you did in the ThemeToggle.

2024-02-15 08:00 UTC, MildTomato commented
> @MildTomato you can still pick the deep-dark theme via the command menu.
Prob need to filter the incoming themes how you did in the ThemeToggle.

I know it's a bit dumb manually filtering all of these areas but I didn't want to have to wait on a feature flag call. we can remove all the filtering later.

2024-02-15 15:56 UTC, fsansalvadore approved these changes
Looks good ✌️

2024-02-15 15:56 UTC, merged