rm unused line-clamp tailwind plugin
supabase/supabase pull request #21057
Opened 2024-02-06 16:38 UTC by jordienr

2024-02-06 16:45 UTC, ivasilov approved these changes

2024-02-07 02:33 UTC, joshenlim approved these changes

2024-02-07 02:35 UTC, joshenlim requested changes
Oh whoops looks like docs and www might be using this? i see a couple of files in www like [this one](https://github.com/supabase/supabase/blob/master/apps/www/components/Nav/MenuItem.tsx#L78) using line-clamp-1 class name

2024-02-07 09:06 UTC, jordienr commented
> Oh whoops looks like docs and www might be using this? i see a couple of files in www like [this one](https://github.com/supabase/supabase/blob/master/apps/www/components/Nav/MenuItem.tsx?rgh-link-date=2024-02-07T02%3A35%3A43Z#L78) using line-clamp-1 class name

Just uninstalling because I installed it in a previous PR and it turns out it's no longer necessary (since tailwind 3.3).
Sorry should have added more context to the PR description 😅.  

> Warning As of Tailwind CSS v3.3 the line-clamp utilities are now included in the framework by default and this plugin is no longer required.

2024-02-08 06:22 UTC, joshenlim approved these changes

2024-02-08 11:51 UTC, merged