Expose Shadcnui toast components from UI and partially implement in storage explorer
supabase/supabase pull request #21308
Opened 2024-02-16 06:24 UTC by joshenlim

2024-02-20 12:16 UTC, ivasilov requested changes
When you move a file to the root folder, it only shows empty space
![Screenshot 2024-02-20 at 13 15 13](https://github.com/supabase/supabase/assets/568291/02482a39-457f-4a11-be3b-7ef0c3c4b6f1)

2024-02-20 12:23 UTC, joshenlim commented
great catch @ivasilov! 🙏  pushed a fix

2024-02-20 13:02 UTC, saltcod approved these changes

2024-02-26 08:39 UTC, ivasilov approved these changes

2024-02-26 08:59 UTC, merged