feat: SQL Editor Charts
supabase/supabase pull request #21638
Opened 2024-02-28 16:13 UTC by jordienr

## What kind of change does this PR introduce?

adds charts to SQL editor

## What is the current behavior?

no charts in SQL editor

## What is the new behavior?

charts in SQL editor

## Additional context

![CleanShot 2024-02-28 at 17 13 25@2x](https://github.com/supabase/supabase/assets/37541088/8a5e6767-d001-4d7a-b2ea-07e1cdd3b13c)

2024-02-28 17:48 UTC, saltcod commented
![screenshot-2024-02-28-at-14 18 14](https://github.com/supabase/supabase/assets/105593/660f2907-9690-40c8-9b9c-d154fdcd024f)

2024-02-29 09:06 UTC, joshenlim commented
could add a draggable marker here between the chart and the control panel (like how we do for the code editor and the utility panel)
![image](https://github.com/supabase/supabase/assets/19742402/fbc61f47-a635-42d3-9b2b-064de5a0ba84)

2024-02-29 09:07 UTC, joshenlim commented
Possible to show axis legends based on the selected columns? The x axis probably should be dynamic based on the column type (if possible) - e.g shouldnt be a date if the values are numbers

![image](https://github.com/supabase/supabase/assets/19742402/6a51f233-d329-4e9b-aa2d-a486f83451cd)

2024-02-29 09:09 UTC, joshenlim commented
(on the fence) Am thinking the export options could be dynamic based on the tabs
results -> CSV, markdown, JSON
charts -> export as png? not sure what other forms might be useful

![image](https://github.com/supabase/supabase/assets/19742402/de0a35a9-a233-4df2-a910-20afa82ee47e)

2024-03-01 10:50 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/UtilityPanel.tsx
> +        <Tabs_Shadcn_ defaultValue="results" className="w-full h-full">
<div className="h-full ..
  <component className="h-full ..
  
  
suss...

2024-03-01 10:52 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/UtilityActions.tsx
> +                <div className="w-6 flex items-center justify-center">
this div doesn't do anything

2024-03-01 10:52 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/ResultsDropdown.tsx
> +            <p>Copy as JSON</p>
remove `<p>` - not required

2024-03-01 10:52 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/ResultsDropdown.tsx
> +          <DropdownMenuItem onClick={onCopyAsJSON} className="space-x-2">
`flex gap-2`

2024-03-01 10:53 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/UtilityPanel.tsx
> +        <Tabs_Shadcn_ defaultValue="results" className="w-full h-full">
non blocker

2024-03-01 10:53 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/UtilityActions.tsx
> +                <div className="w-6 flex items-center justify-center">
non blocker

2024-03-01 10:53 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/ResultsDropdown.tsx
> +            <p>Copy as JSON</p>
non blocker

2024-03-01 10:53 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/ResultsDropdown.tsx
> +          <DropdownMenuItem onClick={onCopyAsJSON} className="space-x-2">
non blocker

2024-03-01 10:54 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/SQLEditor.tsx
> +              </div>
should we fix this component? this looks like terrible DX

2024-03-01 10:55 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/ChartConfig.tsx
> +                  title="Swap X and Y axis"
nice

2024-03-01 10:57 UTC, MildTomato requested changes

2024-03-01 10:57 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/ChartConfig.tsx
> +            <Checkbox
use Checkbox_shadcn ?

This is a change I think is worth doing to reduce refactor later.

2024-03-01 10:58 UTC, MildTomato commented on apps/studio/components/interfaces/SQLEditor/UtilityPanel/ChartConfig.tsx
> +          <div className="h-full">
useless div?
move h-full to `<ResizablePanel/>`

2024-03-01 11:00 UTC, ivasilov approved these changes

2024-03-01 12:37 UTC, MildTomato approved these changes

2024-03-01 12:38 UTC, merged

2024-03-04 22:06 UTC, blechatellier commented
Great stuff, any plan to be able to create a custom dashboard using multiple charts (like geckoboard)?

2024-03-06 21:10 UTC, zedeus commented
Any plans to add this to the log explorer?