feat: alert for white space on field names
supabase/supabase pull request #22097
Opened 2024-03-18 22:28 UTC by Hallidayo

## What kind of change does this PR introduce?

Supabase Studio - Table Editor

## What is the current behavior?

From the table editor you can add/update column names with an starting or ending white space which can cause issues when querying.

## What is the new behavior?

An error now appears which does not allow the user to do this.

https://github.com/supabase/supabase/assets/22655069/0d91b799-d242-451e-9b5c-4b5454831482

## Additional context

Closes #22089

2024-03-19 04:37 UTC, encima approved these changes
The check makes sense. Is there a reason you chose not to automatically strip the whitespace and alert the user on the action that was taken?

2024-03-19 09:15 UTC, encima requested changes
On reflection, it is probably better to fix and alert rather than alert as I cannot think of a use case where leading or trailing whitespace in tables would be wanted

2024-03-20 02:59 UTC, onurusluca commented
@encima That was my thought also. Never heard of a case where you'd need whitespace on a row name. It will just be headache to know where is the problem because API says "Row `application_logs ` doesn't exist.

2024-03-22 03:32 UTC, joshenlim commented
yeap agreed here that white spaces should just be automatically trimmed - we do that in several parts of the dashboard too like table names, bucket names etc

2024-03-22 05:28 UTC, joshenlim commented
Closing in favour of https://github.com/supabase/supabase/pull/22170

2024-03-22 05:28 UTC, closed without merging