Chore/allow disabling public schema
supabase/supabase pull request #22603
Opened 2024-04-09 17:14 UTC by saltcod

2024-04-10 01:42 UTC, inian commented on apps/studio/components/interfaces/Settings/API/PostgrestConfig.tsx
> +                                    API endpoints will not be created for the `public` schema. You
You will not be able to query tables and views in the public schema via postgREST and supabase-js.

2024-04-10 17:25 UTC, saltcod commented on apps/studio/components/interfaces/Settings/API/PublicSchemaNotEnabledAlert.tsx
> +        <AlertDescription_Shadcn_ className={context === 'docs' ? 'grid gap-3 !-mt-7' : ''}>
sorry, this nonsense required b/c docs page piles on its own custom css overriding (ruining) everything.

2024-04-12 02:14 UTC, alaister requested changes
Looking good!

There seems to be an issue where changing any of the items in the exposed schemas field submits the form:

https://github.com/supabase/supabase/assets/10985857/7d8d36fe-bcd8-4989-9ed1-8f4a83908433

Also a couple of small cleanup things:

2024-04-12 02:14 UTC, alaister commented on apps/studio/components/interfaces/Settings/API/PostgrestConfig.tsx
> +
```suggestion
```

2024-04-12 02:14 UTC, alaister commented on apps/studio/components/interfaces/Settings/API/PostgrestConfig.tsx
> +        console.log('schemas', config?.db_schema)
```suggestion
```

2024-04-12 02:14 UTC, alaister commented on apps/studio/components/interfaces/Settings/API/PostgrestConfig.tsx
> +        //}, [config])
```suggestion
```

2024-04-12 03:09 UTC, alaister approved these changes
We can fix the auto submission issue in a follow up PR 👍

2024-04-12 11:26 UTC, merged

2024-04-13 23:04 UTC, GaryAustin1 commented
Oh, goodie,  one more thing to check when things are going wrong.  Please warn them what a bad idea this is unless they know what they are doing.