feat: connect flutter example
supabase/supabase pull request #22693
Opened 2024-04-13 15:49 UTC by Hallidayo

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Supabase Connect - Flutter

## What is the current behavior?

No current Flutter example on the connect examples

## What is the new behavior?

Flutter example added to connect:

https://github.com/supabase/supabase/assets/22655069/3ca37123-635a-4592-aac9-01a09cdcdd78

## Additional context

@dshukertjr - Is it okay if you check this over and is it okay for a basic flutter example?

2024-04-14 01:41 UTC, dshukertjr requested changes
Hey @Hallidayo ,

Thanks for working on this! What you have is a great starting point! Just a few thoughts from me.

First, I don't think we need to include `pubspec.yaml` file sample as other JS projects don't include `package.json` files either. 

Second, what do you think about making the `main.dart` tab the left most tab, and having the following content? I think most people will just take a look at the first tab, so it's important for the first tab to contain the essential information to initialize Supabase and nothing else.

```dart
import 'package:supabase_flutter/supabase_flutter.dart';

Future<void> main() async {
  await Supabase.initialize(
    url: ${projectKeys.apiUrl ?? 'your-project-url'},
    anonKey: ${projectKeys.anonKey ?? 'your-anon-key'},
  );
  runApp(MyApp());
}
```

Then we can create another tab called `lib/home_page.dart`, and put the content of the `HomePage` widget there.

2024-04-15 18:51 UTC, Hallidayo commented
Hi @dshukertjr - Thank you for having a look at the pull. I have made the changes but I've had to rename the second tab due to the tabs being the same name so I've named the tab `lib/main.dart (app)` is this okay or should another name for the tab be used?

2024-04-16 03:12 UTC, dshukertjr approved these changes
Thank you so much for this! This is awesome!

2024-04-16 04:21 UTC, alaister approved these changes

2024-04-16 04:33 UTC, merged