dev,feat: migrate docs to app router pt 1
supabase/supabase pull request #23101
Opened 2024-04-21 17:04 UTC by charislam

2024-04-22 05:33 UTC, MildTomato commented
Just had a brief look through changes.

What about using one Layout (which is a "use client") which uses next/navigation to determine which menu id to use.

Could also use one page file [using a catch all](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#catch-all-segments).

2024-07-01 09:10 UTC, fsansalvadore requested changes

2024-07-01 09:10 UTC, fsansalvadore commented on apps/docs/app/[...slug]/_page.tsx
> +const CatchAllPage = async ({ params }: { params: Params }) => {
I tried this on the preview but it responds with a 500 error page.

<img width="1473" alt="Screenshot 2024-07-01 at 11 07 03" src="https://github.com/supabase/supabase/assets/25671831/de8e6fb6-06f0-4a1c-aaf4-158df6722a29">

2024-07-01 09:10 UTC, fsansalvadore commented on apps/docs/app/[...slug]/_page.tsx
> +const CatchAllPage = async ({ params }: { params: Params }) => {
And maybe worth keeping this part as a separate PR to reduce scope? @charislam

2024-07-03 14:21 UTC, fsansalvadore approved these changes

2024-07-03 14:25 UTC, merged