Update Nuxt 3 User Management example
supabase/supabase pull request #23416
Opened 2024-04-29 15:30 UTC by Shooteger

Updating package versions, as well as .lock file. Adding .env-example file and set runtimeConfig with supabase key

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

It updates the Nuxt 3 User Management example. Newer packages versions to stay accurate, as well as introduce the usage of .env variables.

## What is the current behavior?

-

## What is the new behavior?

-

## Additional context

-

2024-04-29 15:31 UTC, Shooteger commented
Issue to PR here: #23413

2024-05-06 08:18 UTC, sergor5 commented
@Shooteger , I think the handle_new_user function and the trigger of it are missing too.

Could you add it?

 https://github.com/supabase/supabase/blob/master/examples/user-management/nextjs-user-management/README.md

```sql
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
```

2024-05-08 06:50 UTC, sergor5 requested changes

2024-05-08 06:50 UTC, sergor5 commented on examples/user-management/nuxt3-user-management/README.md
> +  insert into public.profiles (id, full_name, avatar_url)
as we are creating the profiles table with an username column and it is a unique one:
```sql
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);
```
you probably should update this as:
```sql
begin
  insert into public.profiles (id, username, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

2024-05-08 06:50 UTC, sergor5 commented on examples/user-management/nuxt3-user-management/README.md
> +### 4. Env vars
You can rename the step sections with a proper number

2024-05-08 06:50 UTC, sergor5 commented on examples/user-management/nuxt3-user-management/README.md
> +Iniate a new project in Nuxt 3 with `npx nuxi@latest init <project-name>`.
After initing the project, the nuxi cli supports auto-installing the modules now as:
```bash
npx nuxi module add supabase
```
so you could make it as the step 2

2024-05-08 06:50 UTC, sergor5 commented on examples/user-management/nuxt3-user-management/README.md
> +  insert into public.profiles (id, full_name, avatar_url)
also, the table should already be created in the "Database Schema" step. Remove the create part in the Postgres Row level security" section

2025-10-03 15:37 UTC, closed without merging