feat: docs ai warning removal
supabase/supabase pull request #23427
Opened 2024-04-29 22:04 UTC by Hallidayo

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Feature - Supabase Docs - Ask AI

## What is the current behavior?

Their is an alert which appears which tells the user about the ai being experimental. This makes the page of the window really small.

## What is the new behavior?

Experimental button is now a tooltip and the warning is removed:

https://github.com/supabase/supabase/assets/22655069/4e61c8bd-8af9-44ef-ab6c-d7323c92c32b

## Additional context

Closes #22714

2024-04-30 15:10 UTC, charislam requested changes
Thanks @Hallidayo! I'd rather keep a very explicit, in-your-face warning message about this. I think it's important to prompt users to take a pause for reflection before running anything against their database, and the tooltip is easy to ignore.

There's probably room to expand the height of the entire dialog on most screens so you have more reading space despite the disclaimer, perhaps we can do that instead?

2024-05-01 21:19 UTC, Hallidayo commented
Hi @charislam - Just reverted the original changes and increased the window a little as well:

<img width="955" alt="Screenshot 2024-05-01 at 22 05 51" src="https://github.com/supabase/supabase/assets/22655069/a1fe92a4-a51f-45a9-bf19-20bfda5eb6c2">

2024-05-03 19:48 UTC, charislam commented on packages/ui-patterns/Cmdk/CommandMenu.tsx
>        ? 'min(600px, 50vh)'
Thanks @Hallidayo! Really appreciate you going along with the changes 😄 IIRC it is this line actually that sets the height on the AI pages (it's already bigger than the usual but I guess we can increase it even further)

2024-05-23 20:19 UTC, Hallidayo commented
Hi @charislam - Thanks for having a look at this, I've just increase the content height a little as well

2024-07-01 19:38 UTC, charislam commented
Thanks @Hallidayo and sorry for the delay in getting back to this! Height looks good, but the backdrop filter seems to have disappeared (might be fixed by merging and fixing conflicts 🤔 perhaps)

<img width="390" alt="image" src="https://github.com/supabase/supabase/assets/26616127/e6d112f0-40a1-4315-b0c5-1f5d9602eb62">

2024-07-02 20:18 UTC, Hallidayo commented
Hi @charislam -  no problem thank you for looking over this one! Just resolved the merge conflict now.

2024-07-03 13:25 UTC, charislam approved these changes
Awesome, thanks!

Checks: checked command menu in preview (docs)

2024-07-03 13:35 UTC, merged