chore: Update Realtime Nav constants
supabase/supabase pull request #25967
Opened 2024-05-09 17:57 UTC by k-ison

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Remove BYOD on Realtime Nav constants

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2024-05-09 18:07 UTC, w3b6x9 requested changes
@k-ison let's remove the markdown file as well

2024-05-09 18:11 UTC, k-ison commented
> @k-ison let's remove the markdown file as well

@w3b6x9 got it, will update. I thought when Copple said "this can live in the repo" from the RFC meant we can keep the mdx file.

2024-05-09 18:42 UTC, w3b6x9 approved these changes

2024-05-09 18:44 UTC, merged

2024-05-30 16:30 UTC, felipecrs commented
Sorry guys, but why was this page removed? This PR is not explaining anything.