Fixed : Spacing for Simple APIs
supabase/supabase pull request #26495
Opened 2024-05-17 19:23 UTC by akar016012

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

Bug Fix

## What is the current behavior?

![image](https://github.com/supabase/supabase/assets/61394999/86520c21-2653-44ad-a6a9-8aedc23bc7cc)

## What is the new behavior?

![image](https://github.com/supabase/supabase/assets/61394999/69751136-2085-4cf9-ba29-b4e7d5ce4412)

## Additional context

added mt-16 to add a top margin so that the content is not cutoff

2024-05-22 14:28 UTC, fsansalvadore requested changes
Thanks @akar016012, I left a few suggestions.

2024-05-22 20:44 UTC, akar016012 commented on apps/www/pages/database/Database.tsx
> +        <SectionContainer className="mb-48">
no its not!
![image](https://github.com/supabase/supabase/assets/61394999/6713717c-8cae-48de-9e8a-63e9d0587d6d)

2024-05-22 20:48 UTC, akar016012 commented
> Thanks @akar016012, I left a few suggestions.

Thank you, very helpful! 💯

2024-05-23 10:16 UTC, fsansalvadore commented on apps/www/pages/database/Database.tsx
> +        <SectionContainer>
This was fine actually, lets stick for the Auth page for now 👍

2024-05-23 10:33 UTC, fsansalvadore approved these changes

2024-05-23 11:00 UTC, merged

2024-05-23 11:01 UTC, fsansalvadore commented
Merged, thanks @akar016012 🎉

2024-05-23 11:02 UTC, fsansalvadore commented
#26392