Docs: Add section on logical replication for setting up CDC from Supabase to a destination
supabase/supabase pull request #27087
Opened 2024-06-07 10:00 UTC by encima

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Docs update

## What is the current behavior?

We only have a short guide on setting up replication and coverage of publications is primarily in the context of Realtime and/or within the DB

## What is the new behavior?

A section dedicated to logical replication, the configuration and pitfalls as well as individual guides for setting it up with tools like Artie, Estuary, Airbyte etc

## Additional context

Add any other context or screenshots.

2024-06-07 18:33 UTC, charislam requested changes
Thanks @encima!

Super useful to have this content.

I've read everything but haven't gone through to make fine-grained suggestions because I have a general comment about the voice: it's a big change from the voice of the rest of our docs -- other docs content in general is more neutral, less breezy, and less familiar.

I'm not opposed to different writers having slightly different styles (it's kind of inevitable) but I think the difference in these is a bit too abrupt. Would it be possible for you to rewrite this in a bit more of a neutral tone? (If you want some pointers or examples or for me to rewrite some sections for you, just let me know.)

Some examples of docs that hew closer to our usual tone:

- https://supabase.com/docs/guides/auth
- https://supabase.com/docs/guides/auth/architecture
- https://supabase.com/docs/guides/ai/going-to-prod

In general, using "you" is good and sounds friendly, but too much second person, and the tone can get in the way of reading the content

2024-06-07 18:33 UTC, charislam commented on apps/docs/components/Navigation/NavigationMenu/NavigationMenu.constants.ts
> +        { name: 'FAQ', url: '/guides/database/replication/faq' },
```suggestion
        { name: 'FAQ', url: '/guides/database/replication-cdc/faq' },
```

2025-05-21 13:46 UTC, encima commented
It's been a while for this one and it has seen one or two rewrites.

This latest version should call out the differences between pg17 and others, as well as reducing the walls of text. set up instructions for different cdc tools are in a tab component

2025-05-26 20:38 UTC, charislam approved these changes

2025-05-28 08:28 UTC, merged