[Fix #27119] Update PKCE example code on with-nextjs example
supabase/supabase pull request #27184
Opened 2024-06-11 15:14 UTC by siraom15

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

FIX #27119: Update PKCE code example

## What is the current behavior?

Docs point to https://github.com/supabase/supabase/tree/master/examples/user-management/nextjs-user-management as example, this is some old example,
docs refer to token_hash and type

## What is the new behavior?
Now docs refer to `code`
Docs Updated to use `code` from PKCE flow and change get session function from `verifyOtp` to `exchangeCodeForSession`

2024-06-11 22:25 UTC, charislam requested changes
Thanks @siraom15!

The `token_hash` method is actually the more updated, recommended way of doing this. The main problem with this guide is actually that it neglects the step where you update the email tempate to send the `token_hash`: see [Step 6 here](https://supabase.com/docs/guides/auth/server-side/nextjs?queryGroups=router&router=app).

I think it would be better to keep the `token_hash`, but add a step to update the email template instead.

2024-06-12 01:23 UTC, siraom15 commented
Hi, @charislam 

I have revert the code to use `token_hash` and update docs.
Do you have any suggestion?
<img width="1001" alt="image" src="https://github.com/supabase/supabase/assets/51380509/b13abf3d-c5e7-4500-a577-9d5503d01199">

2024-06-12 15:44 UTC, charislam approved these changes
Looks great! Thanks @siraom15!

2024-06-12 15:44 UTC, charislam commented on apps/docs/content/guides/getting-started/tutorials/with-nextjs.mdx
> +Change the email template to support a server-side authentication flow following these steps:
```suggestion
Before we proceed, let's change the email template to support sending a PKCE code:
```

2024-06-12 15:55 UTC, merged