feat: swift guide for connect
supabase/supabase pull request #27541
Opened 2024-06-25 16:40 UTC by Hallidayo

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Supabase Connect - Swift

## What is the current behavior?

No current Swift example on the connect examples

## What is the new behavior?

Swift example added to connect:

https://github.com/supabase/supabase/assets/22655069/805d03de-877d-4897-8e8d-056964ca403d

## Additional context

@grdsdev  - Is it okay if you check this over and is it okay for a basic Swift example?

2024-06-25 17:22 UTC, grdsdev requested changes
Thanks for adding this, just requested some examples simplification.

2024-06-25 17:22 UTC, grdsdev commented on apps/studio/components/interfaces/Home/Connect/content/swift/supabaseswift/content.tsx
> +        <ConnectTabTrigger value="ToDoModel.swift" />
```suggestion
        <ConnectTabTrigger value="Todo.swift" />
```

2024-06-25 17:22 UTC, grdsdev commented on apps/studio/components/interfaces/Home/Connect/content/swift/supabaseswift/content.tsx
> +      <ConnectTabContent value="ToDoModel.swift">
```suggestion
      <ConnectTabContent value="Todo.swift">
```

2024-06-25 17:40 UTC, Hallidayo commented
@grdsdev - Thank you for checking over, I've just committed the suggestions.

2024-06-25 17:44 UTC, grdsdev approved these changes

2024-06-28 13:09 UTC, ivasilov approved these changes
Tested on Studio staging, looks good.

2024-06-28 13:09 UTC, merged