correct typo
supabase/supabase pull request #27784
Opened 2024-07-03 21:11 UTC by clarotech

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

 docs update - typo correction

## What is the current behavior?

Incorrect grammar

## What is the new behavior?

Corrected grammar

## Additional context

None

2024-07-04 08:56 UTC, fsansalvadore commented
Thanks @clarotech.

There seems to be a prettier error, please run `npm i && npm run format` locally to fix it.

2024-07-04 16:37 UTC, charislam approved these changes
Thanks @clarotech!

2024-07-05 15:41 UTC, charislam requested changes
prettier issues pointed out above 😄 just changing the review status to reflect it

2025-11-07 13:50 UTC, Hallidayo commented
Hi @clarotech - We’re doing a bit of housekeeping and plan to close out PRs that have been inactive for more than 3 months.
If you’re still interested in landing this, feel free to fix any merge conflicts and reopen it. Thanks!

2025-11-07 13:50 UTC, closed without merging