Improve snippet organization in SQL Editor
supabase/supabase pull request #27881
Opened 2024-07-09 15:36 UTC by joshenlim

2024-07-10 01:07 UTC, alaister reviewed
Sometimes when I move the currently selected snippet (even to the same folder), it gets stuck in a loading state:
<img width="159" alt="Screenshot 2024-07-10 at 10 49 16" src="https://github.com/supabase/supabase/assets/10985857/d96dbf00-8775-408f-a4fa-fe6082a18e25">

2024-07-12 10:49 UTC, joshenlim commented
Okay just pushed a fix for the issue you reported :)

2024-07-15 04:43 UTC, alaister approved these changes
Looking good!

I can't seem to use this button to create a snippet?
<img width="370" alt="Screenshot 2024-07-15 at 14 42 22" src="https://github.com/user-attachments/assets/d92d36f2-7e6d-4470-a405-e45891f70954">

Also another thing I did notice is snippets don't seem to auto-rename anymore?


Tested so far:
- creating a snippet
- creating a folder
- moving a snippet from root to a folder
- moving a snippet back to root
- moving a snippet from one folder to another

2024-07-15 04:43 UTC, alaister commented on apps/studio/hooks/ui/useFlag.ts
> +
Remove this? 😅
```suggestion
```

2024-07-15 05:54 UTC, joshenlim commented on apps/studio/hooks/ui/useFlag.ts
> +
oh crap hahahaha good catch!

2024-07-15 09:34 UTC, alaister requested changes
whoops accidentally approved before

2024-07-16 08:59 UTC, alaister approved these changes
LGTM!

Finished testing:
- creating a snippet inside a folder
- renaming a snippet inside a folder
- sharing a snippet in a folder
- unsharing a snippet
- opening in a new tab

2024-07-17 04:23 UTC, merged