chore update pricing page / compute wording
supabase/supabase pull request #28017
Opened 2024-07-16 10:54 UTC by fsansalvadore

Update copywriting on pricing page.

2024-07-16 11:03 UTC, mikeridley requested changes

2024-07-16 11:03 UTC, mikeridley commented on apps/docs/content/guides/platform/billing-faq.mdx
> +The Pro plan has a spend cap enabled by default to keep costs under control. If you want to scale beyond the plans' included quota, switch off the spend cap to pay for additional usage beyond the pla
Should be plan's not plans'

2024-07-16 11:03 UTC, mikeridley commented on apps/www/components/Pricing/PricingAddons.tsx
> +      "The Pro plan has a spend cap enabled by default to keep costs under control. If you want to scale beyond the plans' included quota, simply switch off the spend cap to pay for additional resour
Change plans' to plan's

2024-07-19 07:19 UTC, mikeridley approved these changes

2024-07-19 07:37 UTC, kevcodez approved these changes

2024-07-19 07:39 UTC, merged