docs: add key encryption docs
supabase/supabase pull request #28369
Opened 2024-08-04 18:03 UTC by Ziinc

Adds docs for Logflare db encryption.

Pre-merge todos:
- [ ] cloak PR should be merged
- [ ] cli should be bumped
- [ ] self host docker-compose should be bumped

2025-09-25 05:51 UTC, ChrisChinchilla requested changes
One tiny grammar nit, but aside from that all good!

2025-09-25 05:51 UTC, ChrisChinchilla commented on apps/docs/docs/ref/self-hosting-analytics/introduction.mdx
> +Once migration is complete, the retired key can be safely removed.
```suggestion
Once migration is complete, you safely remove the retired key.
```

2025-11-04 09:26 UTC, ChrisChinchilla approved these changes

2025-11-04 09:28 UTC, ChrisChinchilla commented
@supabase/dev-workflows Are you able to review so we can merge this PR?

2025-11-04 10:11 UTC, jgoux approved these changes

2025-11-04 10:11 UTC, merged