chore: Migrate all `feather` icons to `lucide` icons
supabase/supabase pull request #29038
Opened 2024-09-02 11:33 UTC by ivasilov

2024-09-03 16:41 UTC, saltcod approved these changes

2024-09-04 09:47 UTC, fsansalvadore requested changes

2024-09-04 09:47 UTC, fsansalvadore commented on apps/www/data/Developers.tsx
> +          icon: Calendar,
@ivasilov watch out, the calendar icon on the "Events and webinars" is an actual calendar 😁
You probably want the { Calendar } from lucide-react.

<img width="796" alt="Screenshot 2024-09-04 at 11 34 25" src="https://github.com/user-attachments/assets/3486caa9-91e5-4416-9762-4534cc4687c9">

2024-09-04 11:33 UTC, fsansalvadore approved these changes
Looks all good on www and docs 👍

2024-09-04 11:46 UTC, merged