Chore/menu expand preference
supabase/supabase pull request #29297
Opened 2024-09-13 19:35 UTC by saltcod

2024-09-14 06:17 UTC, MildTomato requested changes

2024-09-14 06:17 UTC, MildTomato commented on apps/studio/components/interfaces/Account/Preferences/ThemeSettings.tsx
> +        <div className="grid grid-cols-12">
`<FormItemLayout isReactForm={false} />`

2024-09-17 13:22 UTC, MildTomato approved these changes

2024-09-17 13:30 UTC, saltcod commented on packages/ui-patterns/form/Layout/FormLayout.tsx
> +      'flex-row-reverse': '',
:chefs_kiss:

2024-09-17 13:56 UTC, merged