add loki log drain form
supabase/supabase pull request #29848
Opened 2024-10-11 17:07 UTC by jordienr

2024-10-11 20:22 UTC, Ziinc requested changes

2024-10-11 20:22 UTC, Ziinc commented on apps/studio/components/interfaces/LogDrains/LogDrainDestinationSheetForm.tsx
> +      header1_key: defaultValues?.config?.header1_key || '',
Should use the same header logic as http destination, can be one or more headers with the application/json header set by default

2024-10-11 20:22 UTC, Ziinc commented on apps/studio/components/interfaces/LogDrains/LogDrainDestinationSheetForm.tsx
> +      header1_key: defaultValues?.config?.header1_key || '',
Should be the `headers` key

2024-10-16 06:39 UTC, Ziinc approved these changes

2024-10-21 14:37 UTC, saltcod commented
![screenshot-2024-10-21-at-12 06 52](https://github.com/user-attachments/assets/27e22cf5-d985-482c-89b3-4342b468562b)

2024-10-22 15:40 UTC, saltcod approved these changes

2024-10-23 11:50 UTC, merged