fix/supavisor not working with external Postgres database
supabase/supabase pull request #30010
Opened 2024-10-21 13:07 UTC by pikaping

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.
YES

## What kind of change does this PR introduce?

Fixed an issue where Supavisor was not correctly connecting to an external Postgres database.
Moved Supavisor secrets (secret_key_base and vault_enc_key) from docker-compose.yml to be loaded from the .env file for better security and flexibility.
Added an example of these new secrets to the .env.example file with its default values it had.

## What is the current behavior?

Issue url: https://github.com/supabase/supabase/issues/30009
Supavisor won't connect to external Postgres DB. Also lack of Supavisor secrets customization.

## What is the new behavior?

Supavisor connects to external Postgres DB without any problem and healthcheck works. Also all Supavisor secrets are now customizable.

## Additional context

![image](https://github.com/user-attachments/assets/fd7c1790-e4c6-4cc4-899e-30421205c2f4)

2024-10-30 20:37 UTC, pikaping commented
is anything missing?

2024-11-05 19:28 UTC, pikaping commented
@Hallidayo  Thank you for the link. Do I need to do anything additional for this to be merged and released?

2024-11-21 14:36 UTC, pikaping commented
hello?

2024-11-21 14:53 UTC, avallete requested changes
Hey @pikaping !

Thank you for your contribution, it looks good to me, we just need to ensure that the default behavior with embed postgres database works by default.

2024-11-21 14:53 UTC, avallete commented on docker/docker-compose.yml
> +      - VAULT_ENC_KEY=${POOLER_VAULT_ENC_KEY}
**issue**

Those two values aren't available in the `.env.example` we'll need to add them in it with their default value so the `cp .env.example .env && docker-compose up` can start the stack with default settings.

2025-07-14 10:52 UTC, closed without merging