chore: Replace "Allow Support Access" checkbox with toggle and reposition above send button
supabase/supabase pull request #30470
Opened 2024-11-14 12:31 UTC by monicakh

## What kind of change does this PR introduce?

1. Converted "Allow Support Access" from a checkbox to a toggle switch
2. Repositioned the "Allow Support Access" control above the "Send" button

## Additional context

<img width="490" alt="image" src="https://github.com/user-attachments/assets/06d64ed0-1f63-4e2a-97a4-bbc2d27e5518">

2024-11-27 11:39 UTC, CarelFdeWaal commented
> Thanks @monicakh. I was not aware of this PR. Here is the context: [Notion task](https://www.notion.so/Ticket-View-Request-permission-to-use-AI-13e5004b775f8071afa7da806e11e03a?pvs=8&n=github_linkback). Perhaps we incorporate the new wording(https://github.com/supabase/supabase/pull/30540/files) also into this design.

@monicakh see discussion: https://supabase.slack.com/archives/C0429V78ACX/p1732687370649219
(Meanwhile it should not block other PR)

2024-11-27 11:58 UTC, MildTomato commented
Some things I noticed

- we are storing in the form the state, but also have a useState. so there's some dupication
- using deprecated `<Toggle />` component
- I've restored the old style of submit button as it looked a bit odd to me

2024-11-27 12:02 UTC, MildTomato commented on apps/studio/components/interfaces/Support/SupportFormV2.tsx
> +  const Divider = () => {
`<Seperator/>` component

2024-11-27 12:23 UTC, MildTomato commented
updated styling a bit

<img width="824" alt="Screenshot 2024-11-27 at 20 23 05" src="https://github.com/user-attachments/assets/6f497e3b-bb44-49be-8bce-8758776be212">

2024-11-28 13:49 UTC, CarelFdeWaal approved these changes

2024-11-28 14:28 UTC, staaldraad approved these changes

2024-12-02 13:21 UTC, MildTomato requested changes

2024-12-02 13:28 UTC, MildTomato commented on apps/studio/components/interfaces/Support/SupportFormV2.tsx
> +                        layout="flex"
for more context, the `label` on `<FormItemLayout />` adds a `<label />` element, and it adds a name attribute to it that then allows a click on it to toggle the switch.

2024-12-08 13:55 UTC, monicakh commented on apps/studio/components/interfaces/Support/SupportFormV2.tsx
> +                        layout="flex"
Thanks @MildTomato, I've updated the code as suggested.

Also, here’s how the design looks now:

![image](https://github.com/user-attachments/assets/1c5f453f-ed0c-46ee-9145-e4f57d973833)

2024-12-12 11:09 UTC, MildTomato approved these changes

2024-12-12 11:09 UTC, merged