remove swap usage from DB report
supabase/supabase pull request #30877
Opened 2024-12-04 07:04 UTC by encima

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Current DB Reports page shows Swap usage amongst other infra related information. Swap is set to 1GB regardless of compute size and creates confusion amongst users, when it is mostly distracting

## What is the new behavior?

Swap chart has been removed from the Reports page

## Additional context

Add any other context or screenshots.

2024-12-04 14:30 UTC, carusocv approved these changes
LGTM

2024-12-10 15:19 UTC, joshenlim approved these changes
LGTM! Tested on preview, quick check to ensure that the swap usage chart is removed

2024-12-11 07:58 UTC, Ziinc requested changes
Hiding fully is not good for power users.

2024-12-11 08:11 UTC, Ziinc approved these changes
approving for now as temp solution.

2024-12-18 13:00 UTC, merged