adding yc hackathon blog post + photo
supabase/supabase pull request #30911
Opened 2024-12-05 02:11 UTC by craigcannon

2024-12-05 04:07 UTC, ant-supabase reviewed
- needs a thumbnail
- let's make it photo heavy, we must have photos of each of the winning teams somewhere (official photographer?)
- can maybe append a ton of the other photos to the bottom to show how packed/fun it was
- do we have links to any of the winning repos/demo videos?

worth taking our time and making it 💯 to be worthy of the event itself. was such a good event. We can remove it from the LW email to give us more time to craft it

2024-12-05 04:07 UTC, pamelachia approved these changes

2024-12-05 04:10 UTC, ant-supabase requested changes
still needs some crafting

2025-07-28 20:25 UTC, ivasilov commented
Blog spot has been merged via another PR.

2025-07-28 20:25 UTC, closed without merging