feat: adds data science job description
supabase/supabase pull request #3398
Opened 2021-10-01 14:52 UTC by awalias

@roryw10 has some additions but kaizen

2021-10-01 15:18 UTC, awalias commented
![image](https://user-images.githubusercontent.com/458736/135645317-78660645-a6a0-4827-b618-ad22243c6369.png)

2021-10-04 13:41 UTC, kiwicopple requested changes

2021-10-04 13:41 UTC, kiwicopple commented on about/docs/careers/data-scientists.mdx
> +slug: data-scientists
Can we change this one to data engineer?

2021-10-07 07:31 UTC, kiwicopple approved these changes

2021-10-07 07:32 UTC, merged