fix(typo): fix typos for docs
supabase/supabase pull request #3715
Opened 2021-10-29 23:42 UTC by Isaiah-Hamilton

## What kind of change does this PR introduce?

fixes typos for Docs

## What is the current behavior?

Incorrect spelling.

## What is the new behavior?

Correct spelling

2021-10-31 11:08 UTC, kiwicopple commented on web/docs/guides/database/extensions/plv8.mdx
> +returns set of messages as $$
This one needs to be `setof` !

2021-10-31 11:11 UTC, kiwicopple requested changes
just one change required , otherwise this is great thanks!

2021-10-31 15:35 UTC, Isaiah-Hamilton commented
@kiwicopple all fixed.

2021-11-01 03:16 UTC, kiwicopple approved these changes

2021-11-01 03:16 UTC, merged