Update generate link example
supabase/supabase pull request #4723
Opened 2021-12-29 05:01 UTC by Isaiah-Hamilton

## What kind of change does this PR introduce?

Fix #4720

## What is the current behavior?

#4720

## What is the new behavior?

```js
const { data: user, error } = await supabase.auth.api.generateLink({
  'invite',
  'email@example.com'
})
```

## Additional context

@ichbinedgar is this what you wanted?

2021-12-29 17:20 UTC, ichbinedgar commented
Sorry Isaiah-Hamilton , actually it should be like the following ( you need to remove the `{` `}` characters ) 

```

const { data: user, error } = await supabase.auth.api.generateLink(
  'invite',
  'email@example.com'
)
```

2021-12-29 17:40 UTC, ichbinedgar reviewed
You only need to remove the open and close key characters (`{``}`) from the function, because the first and second parameters are strings, only the third one is an object (the options parameter)

2021-12-29 17:42 UTC, ichbinedgar requested changes
so basically like this:

```
const { data: user, error } = await supabase.auth.api.generateLink(
            'invite',
            'email@example.com'
          )
```

2021-12-29 18:07 UTC, ichbinedgar approved these changes
awesome!

2021-12-29 18:08 UTC, ichbinedgar approved these changes

2022-01-04 13:32 UTC, kiwicopple approved these changes

2022-01-04 13:32 UTC, merged