Update contributing page
supabase/supabase pull request #4933
Opened 2022-01-12 04:10 UTC by Isaiah-Hamilton

## What kind of change does this PR introduce?

Update contributing page.

2022-01-12 17:07 UTC, awalias requested changes

2022-01-12 17:07 UTC, awalias commented on web/docs/handbook/contributing.mdx
> +- [Submit an issue](https://github.com/supabase/supabase/issue).
this one depends on the specific repo I think. Which brings me to something that would  be useful for this page...

we could introduce a small selection of our repos here, maybe a link and one line explanation of each of supabase/supabase, supabase/supabase-js, and supabase/gotrue followed by "explore all repos" which links to https://github.com/orgs/supabase/repositories

2022-01-12 17:07 UTC, awalias commented on web/docs/handbook/contributing.mdx
> +- [Create a pull request](https://github.com/supabase/supabase/pulls).
this one will also depend on which repo they're contributing to so maybe not required as a link just yet

2022-01-13 01:57 UTC, Isaiah-Hamilton commented
@awalias is this what you wanted. Thoughts?
<img width="1392" alt="Screen Shot 2022-01-12 at 8 50 28 PM" src="https://user-images.githubusercontent.com/70828596/149252035-e4276bab-62b1-4b7b-8bb4-0bc0a20c9fa6.png">

2022-01-14 15:43 UTC, kiwicopple approved these changes

2022-01-14 18:08 UTC, awalias requested changes

2022-01-14 18:08 UTC, awalias commented on about/docs/handbook/contributing.mdx
> +    - [supabase/supabase](https://github.com/supabase/supabase/issues)
thanks for the update @Isaiah-Hamilton !

I was actually thinking a separate section above the current list, something like:

```
<h1>How to contribute</h1>

Supabase has many [open source repos](https://github.com/orgs/supabase/repositories). Some of the more popular ones are:
  - [Supabase](link) - Our Dashboard, Websites, and example apps
  - [Supabase-js](link) - A clientside library written in Typescript
  - [Gotrue](link) - Our auth server, written in Go
  - [Realtime](link) - A server for streaming changes from Postgres, written in Elixir 
  - [browse all]((https://github.com/orgs/supabase/repositories))

Here are some ways you can contribute:
  - Sponsor Supabase
  - Start a discussion
  - Submit an issue to one of our [repos]((https://github.com/orgs/supabase/repositories))
... 
```

2022-01-15 01:56 UTC, Isaiah-Hamilton commented
@awalias All updated.
<img width="1392" alt="Screen Shot 2022-01-14 at 8 53 23 PM" src="https://user-images.githubusercontent.com/70828596/149604534-c04a8cb6-e749-48d7-9724-ab8bbaff96df.png">

2022-01-18 20:46 UTC, awalias approved these changes
love it!

2022-01-18 20:46 UTC, merged