Enable new auth settings
supabase/supabase pull request #5304
Opened 2022-02-03 16:06 UTC by Isaiah-Hamilton

## What kind of change does this PR introduce?

Enable the new auth providers for users to use.

## What is the current behavior?

missing notion, zoom, LinkedIn

## What is the new behavior?

added notion, zoom, LinkedIn

## Additional context

https://github.com/supabase/infrastructure/pull/4185

2022-02-04 15:08 UTC, kiwicopple approved these changes

2022-02-04 15:08 UTC, kiwicopple commented on web/sidebars.js
> +            'guides/auth/auth-zoom',
can we sort these alphabetically

2022-02-07 16:12 UTC, kangmingtay requested changes
Hey @Isaiah-Hamilton, you'll also need to add the providers inside the [config file](https://github.com/supabase/supabase/blob/master/studio/pages/api/auth/%5Bref%5D/config.ts#L63-L65) 

You can check that you've added the providers in the right places by searching for all occurrences of `facebook` (for oauth) or `twilio` (for sms) within the studio directory.

Thanks for helping with this 🔥

2022-02-07 16:12 UTC, kangmingtay commented on studio/pages/project/[ref]/auth/settings.tsx
> +                )))}
this makes the default phone provider "textlocal", can we leave the default to use twilio instead?

2022-02-07 16:30 UTC, kangmingtay commented on studio/pages/project/[ref]/auth/settings.tsx
> +            EXTERNAL_LINKEDIN_ENABLED: model.EXTERNAL_LINKEDIN_ENABLED || undefined,
this shouldn't default to undefined

2022-02-07 16:30 UTC, kangmingtay commented on studio/pages/project/[ref]/auth/settings.tsx
> +            EXTERNAL_NOTION_ENABLED: model.EXTERNAL_NOTION_ENABLED || undefined,
likewise, see https://github.com/supabase/supabase/pull/5304/files#r800837298

2022-02-08 15:56 UTC, kangmingtay approved these changes

2022-02-08 17:23 UTC, merged