fix(www): prevent dark flash when light mode
supabase/supabase pull request #5348
Opened 2022-02-07 07:38 UTC by yangshun

## What kind of change does this PR introduce?

Prevents the page from flashing from dark to light if the user selected a light theme (via the footer).

## What is the current behavior?

https://user-images.githubusercontent.com/1315101/152717469-6066bcf2-ce6a-431e-9f1b-06d6dbaf07f6.mp4

See that when the page first loads, the page is black and then it turns white.

## What is the new behavior?

By setting the final class name while the HTML is loading and before the browser first paints to the screen (via `<script>` tags), we can prevent the browser from rendering a version which doesn't match the user's preferences. This technique is being used in [Docusaurus v2](https://github.com/facebook/docusaurus/blob/aa446b7a9c0076e848708e9ea71b8c2e26698be0/packages/docusaurus-theme-classic/src/index.ts).

Also refactored some of the code to be more robust.

2022-02-18 13:08 UTC, thebengeu requested changes

2022-02-18 13:08 UTC, thebengeu commented on www/components/Layouts/Default.tsx
> +    window.localStorage.setItem(MODE_STORAGE_KEY, (!darkMode).toString())
Should `(!darkMode)` be `isDarkMode` instead?

2022-02-18 13:20 UTC, thebengeu commented
I can't figure out why just from looking at the code, but if you refresh when in light mode, the toggle is set to dark mode:

<img width="176" alt="Screenshot 2022-02-18 at 21 18 19" src="https://user-images.githubusercontent.com/1154867/154689982-b15271bb-948f-46b1-a4f9-63d10029c25e.png">

2022-02-28 13:00 UTC, thebengeu commented
The default when there's nothing set in `localStorage` is now light mode, I don't think that's intended?

2022-04-26 08:14 UTC, MildTomato commented
@yangshun this ready for another review?

2022-04-26 08:15 UTC, yangshun commented
I don't think so, I'll fix it up soon and test it more thoroughly. Thanks
for the reminder!

Regards,
Yangshun


On Tue, Apr 26, 2022 at 1:14 AM Jonathan Summers-Muir <
***@***.***> wrote:

> @yangshun <https://github.com/yangshun> this ready for another review?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/supabase/supabase/pull/5348#issuecomment-1109491160>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKBCHLBSKJXRSXY7SETOULVG6QVPANCNFSM5NWUXU7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-04 01:41 UTC, MildTomato commented
hey @yangshun, i'm just going to close this pull request for now. feel free to reopen it if you want to work on it again.

2022-05-04 01:41 UTC, closed without merging