feat/logs: Auth logs
supabase/supabase pull request #6397
Opened 2022-04-11 09:56 UTC by Ziinc

Todos:
- [x] add query templates
- [ ] update staging LF endpoint
- [ ] update prod LF endpoint
- [ ] add feature flag
- [ ] add custom renderer

2022-04-29 14:48 UTC, burggraf approved these changes

2022-04-29 15:37 UTC, MildTomato requested changes

2022-04-29 15:37 UTC, MildTomato commented on studio/pages/project/[ref]/auth/auth-logs.tsx
> +      {project && <LogsPreviewer projectRef={project!.ref} queryType="auth" />}
will need to handle padding on the page before merging

2022-04-29 16:07 UTC, MildTomato commented on studio/pages/project/[ref]/auth/auth-logs.tsx
> +      {project && <LogsPreviewer projectRef={project!.ref} queryType="auth" />}
should be fine now

2022-05-04 01:19 UTC, MildTomato approved these changes

2022-05-04 01:19 UTC, merged