chore: details on using the project metrics endpoint
supabase/supabase pull request #6584
Opened 2022-04-27 06:03 UTC by darora

2022-04-27 21:42 UTC, chasers requested changes
Looks good other than that typo!

2022-04-27 21:42 UTC, chasers commented on web/docs/guides/platform/metrics.mdx
> +The endpoint discussed in thsi article is in beta, and the metrics returned by it might evolve or be changed in the future to increase its utility.
thsi > this

2022-04-29 08:40 UTC, kiwicopple commented on web/docs/guides/platform/metrics.mdx
> +The endpoint discussed in this article is not available on self-hosted.
```suggestion
The endpoint discussed in this article is an Enterprise feature and is not available on self-hosted. It is available for all projects until 1st Sept 2022, and then will be disabled for Free-tier and Pro-tier projects.
```

2022-04-29 08:40 UTC, kiwicopple approved these changes

2022-05-04 13:43 UTC, chasers approved these changes

2022-05-05 03:28 UTC, merged