Fix/5778
supabase/supabase pull request #6784
Opened 2022-05-11 16:48 UTC by joshenlim

Resolves https://github.com/supabase/supabase/issues/5778
- Added empty state for column editor for when column has no name yet in the form
- Fixed foreign key selector component not showing updated foreign key config (as highlighted by hieu)

Empty state: will show "This column" until user starts typing into the name field
![image](https://user-images.githubusercontent.com/19742402/167903772-6d89cc88-b2a0-4a38-a5e5-cfd557dadfbc.png)

2022-05-11 16:57 UTC, MildTomato commented on studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx
> +              The foreign key relation will be <span className="text-green-1000">updated</span> as
text-brand-900 ?

2022-05-11 16:57 UTC, MildTomato requested changes
see above

2022-05-13 06:07 UTC, MildTomato commented on studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx
> +              The foreign key relation will be <span className="text-green-900">updated</span> as
did you just resolve that without changing it?
@joshenlim

2022-05-13 06:07 UTC, MildTomato commented on studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx
> +              The foreign key relation will be <span className="text-green-900">updated</span> as
`text-brand-900`

2022-05-13 06:07 UTC, MildTomato commented on studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx
>                <span className="text-green-900">added</span>:
`text-brand-900`

2022-05-13 06:08 UTC, MildTomato requested changes, later dismissed
see comments :D

2022-05-16 06:49 UTC, phamhieu approved these changes

2022-05-20 09:05 UTC, merged