Fix: broken link
supabase/supabase pull request #6819
Opened 2022-05-13 03:55 UTC by Isaiah-Hamilton

## What kind of change does this PR introduce?

Fix a problem with doc links on the API sidebar leading to `/#`.

## What is the current behavior?

Links are leading to `/#` and lead nowhere.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/70828596/168208009-bc188b86-6ee0-4181-a951-c6a9550c43ed.png">

## What is the new behavior?

<img width="509" alt="image" src="https://user-images.githubusercontent.com/70828596/168207947-64fdc34d-929b-414a-82bc-ab05b668a0a4.png">

2022-05-13 05:29 UTC, MildTomato requested changes
Not possible to use Menu.Item, there's meant to be correct markup in that component for Menu Lists

2022-05-19 03:09 UTC, joshenlim commented
seems like Menu.Item doesnt pass down the href correctly - ref Isaiah's first screenshot
it works for internal routing within the dashboard when you click on it, but not for external URLs

2022-05-19 03:19 UTC, joshenlim commented
Heads up - i've added a temp fix to render differently if the ProductMenuItem is `isExternal`

2022-07-03 16:05 UTC, Isaiah-Hamilton commented
will fix this in another pull request

2022-07-03 16:05 UTC, closed without merging