Adds integration docs with SuperTokens
supabase/supabase pull request #6888
Opened 2022-05-19 13:05 UTC by rishabhpoddar

## What kind of change does this PR introduce?

Docs update

## Additional context

Adds docs about how to add SuperTokens auth, create a Supabase JWT, store that in a SuperTokens session, and query Supabase on the frontend and backend.

2022-05-23 06:25 UTC, kiwicopple commented on web/docs/guides/integrations/supertokens.mdx
> +- [SuperTokens blog](https://supertokens.com/blog).
```suggestion
```

I would like to remove the link to the blog - it doesn't directly help with the tutorial above

2022-05-23 06:29 UTC, kiwicopple commented on web/docs/guides/integrations/supertokens.mdx
> +description: "Create a Next.js application secured by Email-Password or Social Login from Stytch, and Supabase's Row Level Security (RLS)."
```suggestion
description: "Create a Next.js application secured by SuperTokens and PostgreSQL Row Level Security."
```

2022-05-23 06:30 UTC, kiwicopple requested changes
a couple of suggestions 

Also would you mind running prettier on this one? Hopefully it will add line breaks after the Headdings

2022-05-23 06:48 UTC, rishabhpoddar commented
> Also would you mind running prettier on this one? Hopefully it will add line breaks after the Headdings

Done! Thanks

2022-05-24 05:58 UTC, jscyo commented
Hey @kiwicopple any update on the status of this PR being merged?

2022-05-30 06:18 UTC, kiwicopple approved these changes

2022-05-30 06:18 UTC, merged