studio: remove publication ALL TABLES toggle
supabase/supabase pull request #7233
Opened 2022-06-09 09:41 UTC by soedirgo

Once removal of superuser access is rolled out, the `postgres` role (which will be used for the dashboard vs. the `supabase_admin` role) won't have the privileges to create ALL TABLES publications, so this will just fail. Specifically, it will succeed in dropping the publication but fail in recreating it, which is *very* bad for Realtime.

There are plans to make it work again w/o a superuser role, at that point we can expose this again.

2022-06-13 06:26 UTC, joshenlim commented on studio/components/interfaces/Database/Publications/PublicationsTables.tsx
> -  const publication = selectedPublication
can we comment these out instead since we have plans to bring these back
and also leave a comment in the code as to why we're commenting these out

2022-06-13 06:26 UTC, joshenlim commented on studio/components/interfaces/Database/Publications/PublicationsTables.tsx
> -            <Table.th key="header-all">
likewise can just comment out for now

2022-06-13 06:27 UTC, joshenlim requested changes
small stuffs

2022-06-13 06:48 UTC, soedirgo commented
updated the PR, PTAL

2022-06-14 02:34 UTC, joshenlim approved these changes

2022-06-14 02:38 UTC, merged