Studio components refactoring and cleanup
supabase/supabase pull request #7453
Opened 2022-06-27 08:41 UTC by gitstart

## What kind of change does this PR introduce?

Feature: These changes moves the the BarChart component to `ui/Charts/BarChart` folder, ensures it has the correct types and creates a Storybook component for it.

## What is the current behavior?

Partially fixes #6249

[issue link](https://github.com/supabase/supabase/issues/6249)
Currently we've got the BarChart in the `components/to-be-cleaned/Charts/ChartRenderer` file, without proper types and stories.

## What is the new behavior?

The BarChart has been moved to `components/ui/charts/BarChart`, with proper types added and stories showing its use with varying props.

<img width="1672" alt="Screenshot 2022-06-21 at 12 20 44" src="https://user-images.githubusercontent.com/5907294/174787807-619b24c9-cbcc-4289-99df-826679f45ad4.png">

2022-06-30 05:48 UTC, gitstart commented
> Hey @gitstart! Thank you for this PR! I wonder if you could remove the old BarChart component and replace with your cleaned instance?
> 
> Looks like there's two to address: https://github.com/supabase/supabase/blob/master/studio/components/to-be-cleaned/Charts/ChartHandler.tsx#L168
> 
> and
> 
> https://github.com/supabase/supabase/blob/master/studio/components/interfaces/Settings/Logs/LogEventChart.tsx#L17
> 
> Appreciate your efforts!

Hey @saltcod Your request has been done. Sorry about the delay

2022-07-11 06:02 UTC, gitstart commented
> > Hey @gitstart! Thank you for this PR! I wonder if you could remove the old BarChart component and replace with your cleaned instance?
> > Looks like there's two to address: https://github.com/supabase/supabase/blob/master/studio/components/to-be-cleaned/Charts/ChartHandler.tsx#L168
> > and
> > https://github.com/supabase/supabase/blob/master/studio/components/interfaces/Settings/Logs/LogEventChart.tsx#L17
> > Appreciate your efforts!
> 
> Hey @saltcod Your request has been done. Sorry about the delay

@saltcod 😄

2022-08-09 19:19 UTC, saltcod commented
Hey @gitstart sorry for the delay on this one. Will review this one along with the other chart PR after launch week. Thanks!

2022-08-10 18:51 UTC, gitstart commented
Okay, sir

2022-08-10 18:51 UTC, gitstart commented
> Hey @gitstart sorry for the delay on this one. Will review this one along with the other chart PR after launch week. Thanks!

Okay, sir

2022-08-11 21:48 UTC, Ziinc requested changes
🙏 appreciate the PR, but as this component is very important and used in many places the review process might be a little longer and more stringent than usual.

as @saltcod has mentioned, please also remove the bar chart from the ChartRenderer to avoid duplicate code.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/to-be-cleaned/Charts/ChartHandler.tsx
> +import { BarChart } from 'components/ui/Charts/BarChart/BarChart'
Please rename BarChart.tsx to index.tsx, so that we can avoid duplicate importing.

2022-08-11 21:48 UTC, Ziinc commented on studio/.storybook/main.js
> +  webpackFinal: async (config) => {
please rebase on master, it has already been added in.

2022-08-11 21:48 UTC, Ziinc commented on studio/.storybook/main.js
> +    '@storybook/addon-actions',
unnecessary, please remove. See other PR.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.stories.tsx
> +const defaultArgs = {
move the default args into the template and spread them into the component. then let `args` override.
```
<BarChart {...{my: 'attr'}} />
```

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.stories.tsx
> +const data = [290, 430, 620, 67, 354, 123, 627, 122].map(val => ({ "ram_usage": val}));
move to defaultArgs and keep logic together.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.stories.tsx
> +  ...defaultArgs,
can be removed once defaultArgs is moved to template.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +  if (focus) {
this entire block should not be here. There should not be any parent-specific logic for this common component, since it is an abstraction.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +  if (focus) {
This logic should be moved to wherever this is relevant (Reports section).

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +      {label ?? attribute}
should only display label.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +    <h3 className={'text-scale-900 ' + (minimalHeader ? 'text-xs' : 'text-sm')}>
should use template string

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +        'text-scale-1200 text-xl font-normal ' + (minimalHeader ? 'text-base' : 'text-2xl')
template string

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +  const date = (
replace this with a `subtitle` prop.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +export function BarChart({
```
const BarChart : React.FC<Props> = ({})=>
```

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +export function BarChart({
```
export default BarChart
```

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +    className="
clear whitespace and keep to single line.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.tsx
> +function numberWithCommas(x: number) {
can remove. unused.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/ui/Charts/BarChart/BarChart.types.ts
> +export type HeaderType = {
the header takes many props that are shared with the bar chart directly. should extend and pick from the bar chart interface.

2022-08-11 21:48 UTC, Ziinc commented on studio/package.json
> +    "@storybook/addon-actions": "^6.5.9",
please remove this dep, unnecessary.

2022-08-11 21:48 UTC, Ziinc commented on studio/postcss.config.js
> +    tailwindcss: {
webpack should pick up tailiwnd already, this change is unnecessary.

2022-08-11 21:48 UTC, Ziinc commented on studio/components/interfaces/Settings/Logs/LogEventChart.tsx
> +import { BarChart } from 'components/ui/Charts/BarChart/BarChart'
see other comment.

2022-08-15 03:29 UTC, gitstart commented
Hey @Ziinc Thanks for the comments, will be working on these in a few

2022-08-22 13:04 UTC, Ziinc commented
Thanks for contributions, will take these changes from here. Closing for now due to conflicts.

2022-08-22 13:04 UTC, closed without merging

2022-08-23 04:07 UTC, gitstart commented
@Ziinc I'd just pushed changes here 😅