Studio components refactoring and cleanup (Line Chart)
supabase/supabase pull request #7454
Opened 2022-06-27 08:43 UTC by gitstart

## What kind of change does this PR introduce?

Feature: These changes move the Area Chart to its own component, adds stories and ensures that it has proper types.

## What is the current behavior?

[issue link](https://github.com/GitStartHQ/client-supabase/issues/47)
Currently we've got the Area Chart in the `components/to-be-cleaned/Charts/ChartRenderer` file, without proper types and stories.

## What is the new behavior?

The Area Chart has been moved to `components/ui/charts/LineChart`, with proper types added and stories showing its use with varying props.

<img width="1672" alt="Screenshot 2022-06-22 at 08 40 37" src="https://user-images.githubusercontent.com/5907294/174972316-1ca54a89-8f97-4e40-a05a-cc0a5ca297fa.png">

## Additional context

There isn't a component called LineChart in the ChartRenderer. I'm assuming that the component that needs to be refactored is the AreaChart, since its the only other component alongside the the BarChart in the ChartRenderer.

2022-07-26 14:33 UTC, gitstart commented
@kiwicopple any update on this?

2022-08-09 19:05 UTC, saltcod commented
Thanks @gitstart!  This is a big PR and we want to make sure we go through it carefully. We'll circle back to it after launch week.

2022-08-11 22:03 UTC, Ziinc requested changes
🙏 thanks for making the PR and moving the charting forward, as this PR is based on the BarChart PR, i have only focused on the area chart stuff.

As you have mentioned, the issue is actually about extracting out the AreaChart portion. However, due to the similarities between AreaChart and a line chart, (just the shading below), we can actually just remove the coloring and it will become a line chart (just need to replace the rechart component). Hence, why I said line chart.

Furthermore, this area chart needs to have a somewhat similar api to the StackedAreaChart component.

2022-08-15 03:36 UTC, gitstart commented
Hey @Ziinc,
Thanks for the review, will be getting back to you in a few.

2022-08-22 05:22 UTC, Ziinc commented
@gitstart thanks for the contribution, I will take over this PR from here so that we can ship these changes faster.

2022-08-22 05:23 UTC, Ziinc approved these changes

2022-08-22 05:24 UTC, Ziinc commented
Will be closing due to conflicts.

2022-08-22 05:24 UTC, closed without merging