added directus+supabase integration guide
supabase/supabase pull request #8065
Opened 2022-08-03 16:45 UTC by erondpowell

## What kind of change does this PR introduce?

Docs guide for integrating Directus + Supabase

## Additional context

I'm not 100% sure how `combined.json`, `gotrue.json`, and `storage.json` got changes. I'm just now seeing them.
I'm guessing when we run `make`?
Please let me know if I need to modify/gitignore these.

2022-08-04 04:44 UTC, thorwebdev requested changes
Thanks @erondpowell, yes, can you please revert the changes in `spec/*`? Thanks.

2022-08-04 06:37 UTC, thorwebdev requested changes

2022-08-04 06:37 UTC, thorwebdev commented on web/docs/guides/integrations/directus.mdx
> +Supabase is strictly developer tooling, making it great for engineers, but its administration app is not suitable for non-technical business users. Directus, by comparison, is also developer tooling,
```suggestion
Supabase is a suite of open-source tools making Postgres databases, file storage, authentication, edge functions and more accessible to developers of all skill levels. Directus is also developer tooling and additionally provides a Data Studio that is safe and intuitive enough for anyone, including non-technical users, to use. This is the crucial bit that gives the two platforms such a strong “network effect.”
```

2022-08-06 22:22 UTC, erondpowell commented
> can you please revert the changes in `spec/*`? Thanks.

@thorwebdev  Done! This one's ready to roll out live, I think.

2022-08-08 04:58 UTC, thorwebdev approved these changes
LGTM, thanks.

@RamiroND @erondpowell you can merge this in whenever we're ready to release. Once merged it will be automatically deployed and published 👍

2022-08-08 15:51 UTC, merged