Update domain regex to accept chrome extension urls
supabase/supabase pull request #8533
Opened 2022-08-19 13:14 UTC by aar2dee2

Issue #8338

## What kind of change does this PR introduce?

Bug fix - input validation for redirect domain urls in Authentication settings

## What is the current behavior?
Chrome extension urls are not allowed when entered in dashboard, but gets accepted using curl

Please link any relevant issues here.
#8338 

## What is the new behavior?
Chrome extension urls may be added through Authentication settings in dashboard 
Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2022-08-19 18:39 UTC, qhofita requested changes
Damage this the sender domain

2022-08-21 18:42 UTC, Isaiah-Hamilton approved these changes

2022-08-30 03:29 UTC, qhofita approved these changes
Fishing

2022-08-30 03:29 UTC, qhofita commented on studio/components/interfaces/Auth/Auth.constants.ts
> -  /^((ftp|http|https):\/\/)?(www.)?(?!.*(ftp|http|https|www.))[a-zA-Z0-9_*-]+(\.[a-zA-Z0-9_*-]+)+((\/)[\w#]+)*(\/\w+\?[a-zA-Z0-9_]+=\w+(&[a-zA-Z0-9_]+=\w+)*)+(?:\.[a-z]+)*(?::\d+)?(?![^<]*(?:<\/\w+>|
Damage

2022-09-05 12:59 UTC, gprieto commented
Looking forward to this ! In the meantime, is there a workaround?

2022-09-26 13:46 UTC, kiwicopple approved these changes
nice!

2022-09-26 13:46 UTC, merged