fix(typos): add github action to prevent typos + fix typos
supabase/supabase pull request #9598
Opened 2022-10-16 23:28 UTC by stavares843

## What kind of change does this PR introduce?

This introduces a Github Action that automatically scans the whole codebase for typos and automatically adds a Pull Request suggesting those code changes.

## What is the current behavior?

No CI to prevent typos.

## What is the new behavior?

With a Github Action to prevent typos, we can avoid typos in the codebase which results in saving time updating either code or docs with typos.

## Additional context

I got to know this project in Hacker News, so I though I could add this contribution 🔨

2022-10-19 03:00 UTC, MildTomato requested changes

2022-10-19 03:02 UTC, MildTomato approved these changes

2022-10-19 03:02 UTC, MildTomato requested changes, later dismissed
sorry, accidentally approved

2022-10-19 07:30 UTC, kiwicopple approved these changes

2022-10-19 07:47 UTC, MildTomato commented
@stavares843

![Uploading Screenshot 2022-10-19 at 3.46.55 PM.png…]()
ok to fix the build error in the studio ?

2022-10-19 07:47 UTC, MildTomato commented
@stavares843

<img width="1365" alt="Screenshot 2022-10-19 at 3 46 55 PM" src="https://user-images.githubusercontent.com/8291514/196628773-27418c0f-2c8f-4e7a-88bf-f57edc46ec2d.png">
ok to fix the build error in the studio ?

2022-10-19 07:49 UTC, MildTomato requested changes
just to fix the build error :D 🚀 

Looks like a component misnamed

2022-10-19 11:38 UTC, stavares843 commented
thanks for reviewing! will check 🔨

2022-10-19 11:59 UTC, stavares843 commented
addressed 🔨

2022-10-19 13:38 UTC, stavares843 commented on i18n/README.fr.md
> -Notre bibliothèque client est modulaire. Chaque sous-bibliothèque est une implémentation autonome pour un seul système externe. C'est l'une des façons dont nous soutenons les outils existants.
reverted this changed and added a `.misspell-fixer.ignore` file, where i added the `i18n` to be whitelisted, will test more to make sure it works 🔨

2022-10-21 14:02 UTC, kiwicopple commented
this is an epic contribution 🔥 

@MildTomato - you OK to merge? You have some requested changes

2022-10-21 14:20 UTC, stavares843 commented
thanks so much @kiwicopple 🎉 This is a great project! I noticed some open positions, I applied for the Support Engineer position 📺

2022-10-24 11:06 UTC, MildTomato commented
@stavares843 still have some builds failing.
Is it building locally?

<img width="1494" alt="Screenshot 2022-10-24 at 7 06 16 PM" src="https://user-images.githubusercontent.com/8291514/197512252-19d428d6-f612-4ec7-95b4-7e453defe7ce.png">

ps. this is great btw 🔥 nice work

2022-10-24 12:40 UTC, stavares843 commented
<img width="1162" alt="Captura de ecrã 2022-10-24, às 13 40 09" src="https://user-images.githubusercontent.com/29093946/197527615-7cbba078-3403-4030-8515-9ebf4b939e00.png">

i also double checked CI, and the latest one is green 🎉 

that one you posted, seems a previous one that was failing 🔨

2022-10-26 12:11 UTC, MildTomato commented
@stavares843 ahh sorry about that, i was looking at wrong thing 🙈 
running checks again now 🚀 !

2022-10-26 12:21 UTC, stavares843 commented
no worries, thanks for running the CI again! 🔨 all green now 🎉

2022-10-28 01:54 UTC, MildTomato approved these changes

2022-10-28 01:55 UTC, MildTomato commented
Just getting a supabase team FE member to review as well, just to double check.
lgtm though 🚀 

thanks @stavares843 - great contribution !

2022-10-28 02:28 UTC, pucho approved these changes
This looks great, thanks for the contribution!

2022-10-28 02:32 UTC, merged

2022-10-28 12:50 UTC, stavares843 commented
thanks 🎉 

here it is, first PR added by the bot 🔨 


https://github.com/supabase/supabase/pull/9916