Create weweb
supabase/supabase pull request #9731
Opened 2022-10-21 09:41 UTC by EWMAs

## What kind of change does this PR introduce?

Create new user doc article on how to integrate a Supabase backend in a WeWeb frontend.

## What is the current behavior?

Not applicable

## What is the new behavior?

Not applicable

## Additional context

This is the doc to include WeWeb in the Supabase Partner Program

2022-10-24 07:33 UTC, awalias approved these changes

2022-10-24 07:33 UTC, awalias commented on apps/reference/docs/guides/integrations/weweb
> +> Realtime is disabled by default in Supabase for better database performance and security. Learn more about [realtime functionalities](https://supabase.com/docs/guides/database#realtime) in our docu
might just wanna change these ones to be relative but otherwise looks great 👍

2022-11-02 08:44 UTC, thorwebdev requested changes
Hey, would you be able to rename the file to `weweb.mdx`, add the necessary metadata (see example ) and add it to the reference: https://github.com/supabase/supabase/blob/master/apps/reference/nav/_referenceSidebars.js#L261

2022-11-02 08:44 UTC, thorwebdev commented on apps/reference/docs/guides/integrations/weweb
> +This guide explains how to connect a Supabase back-end to a WeWeb front-end and then configure all the CRUD operations necessary to build an Admin Portal with user authentication, roles, and permissi
```suggestion
---
id: weweb
title: 'WeWeb'
description: 'Build user interfaces on top of existing databases.'
---

This guide explains how to connect a Supabase back-end to a WeWeb front-end and then configure all the CRUD operations necessary to build an Admin Portal with user authentication, roles, and permissions.
```

2022-11-03 18:44 UTC, saltcod commented
Hey @EWMAs we've just migrated our docs from Docusaurus to NextJS. Apologies for the inconvenience, but would you mind porting these changes to `/apps/docs` instead of `docs/reference`?  You could wait until you have approval here and then move them over, or just do it now would work as well.

Any questions please let me know

Thanks and apologies in advance!

2022-11-09 19:45 UTC, dannykng commented
Closing in favor of https://github.com/supabase/supabase/pull/10217

2022-11-09 19:45 UTC, closed without merging